# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: "annualseasonal_access"
    description: "U.S. Climate Normals Annual / Seasonal Data (Most Recent)."
  - type: bigquery_table
    table_id: "annualseasonal_historical"
    description: "U.S. Climate Normals Annual / Seasonal Data (Historical)."

dag:
  airflow_version: 2
  initialize:
    dag_id: normals_annualseasonal
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "0 3 1 */3 *"  # At 03:00 on day-1 of-month 1 in every 3rd month.
    catchup: False
    default_view: graph

  tasks:
    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: us-climate-normals-annualseasonal
          initial_node_count: 2
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-standard-4
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform
    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "annualseasonal_load"
        startup_timeout_seconds: 600
        name: "load_us_climate_normals"
        namespace: "default"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: us-climate-normals-annualseasonal
        image_pull_policy: "Always"
        image: "{{ var.json.us_climate_normals.container_registry.run_csv_transform_kub }}"
        env_vars:
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "{{ var.json.us_climate_normals.container_registry.dataset_id }}"
          CHUNKSIZE: "500000"
          CURRENT_DATA_TABLE_ID: "{{ var.json.us_climate_normals.normals_annualseasonal.destination_dataset_table_current }}"
          HISTORICAL_DATA_TABLE_ID: "{{ var.json.us_climate_normals.normals_annualseasonal.destination_dataset_table_historical }}"
          DATA_FILE_SURR_KEY_FIELD: "{{ var.json.us_climate_normals.normals_annualseasonal.data_file_surr_key_field }}"
          DEST_FOLDER: "{{ var.json.us_climate_normals.container_registry.dest_folder }}"
          SCHEMA_FILEPATH: "{{ var.json.us_climate_normals.normals_annualseasonal.schema_filepath }}"
          SOURCE_BUCKET: "{{ var.json.us_climate_normals.container_registry.source_gcs_bucket }}"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          CURRENT_DATA_TARGET_GCS_PATH: "{{ var.json.us_climate_normals.normals_annualseasonal.current_data_target_gcs_path }}"
          HISTORICAL_DATA_TARGET_GCS_PATH: "{{ var.json.us_climate_normals.normals_annualseasonal.historical_data_target_gcs_path }}"
          DEST_CURRENT_DATA_FOLDER_NAME: "{{ var.json.us_climate_normals.container_registry.dest_current_data_folder_name }}"
          DEST_HISTORICAL_FOLDER_NAME: "{{ var.json.us_climate_normals.container_registry.dest_historical_data_folder_name }}"
          SOURCE_BUCKET_CURRENT_DATA_FOLDER_NAME: "{{ var.json.us_climate_normals.normals_annualseasonal.source_bucket_current_data_folder_name }}"
          DATA_ROOT_FOLDER: "normals-annualseasonal"
          HIST_FOLDERS_LIST: >-
            ["1981-2010", "1991-2020", "2006-2020"]
          PIPELINE_NAME: "US Climate Normals Hourly Load"
          INPUT_CSV_HEADERS: >-
            [ "station",
              "latitude",
              "longitude",
              "elevation",
              "name",
              "ann-prcp-avgnds-ge001hi", "ann-prcp-avgnds-ge001hi_attributes",
              "ann-prcp-avgnds-ge010hi", "ann-prcp-avgnds-ge010hi_attributes",
              "ann-prcp-avgnds-ge050hi", "ann-prcp-avgnds-ge050hi_attributes",
              "ann-prcp-avgnds-ge100hi", "ann-prcp-avgnds-ge100hi_attributes",
              "ann-prcp-normal", "ann-prcp-normal_attributes",
              "ann-snow-avgnds-ge001ti", "ann-snow-avgnds-ge001ti_attributes",
              "ann-snow-avgnds-ge010ti", "ann-snow-avgnds-ge010ti_attributes",
              "ann-snow-avgnds-ge030ti", "ann-snow-avgnds-ge030ti_attributes",
              "ann-snow-avgnds-ge050ti", "ann-snow-avgnds-ge050ti_attributes",
              "ann-snow-avgnds-ge100ti", "ann-snow-avgnds-ge100ti_attributes",
              "ann-snow-normal", "ann-snow-normal_attributes",
              "djf-prcp-avgnds-ge001hi", "djf-prcp-avgnds-ge001hi_attributes",
              "djf-prcp-avgnds-ge010hi", "djf-prcp-avgnds-ge010hi_attributes",
              "djf-prcp-avgnds-ge050hi", "djf-prcp-avgnds-ge050hi_attributes",
              "djf-prcp-avgnds-ge100hi", "djf-prcp-avgnds-ge100hi_attributes",
              "djf-prcp-normal", "djf-prcp-normal_attributes",
              "djf-snow-avgnds-ge001ti", "djf-snow-avgnds-ge001ti_attributes",
              "djf-snow-avgnds-ge010ti", "djf-snow-avgnds-ge010ti_attributes",
              "djf-snow-avgnds-ge030ti", "djf-snow-avgnds-ge030ti_attributes",
              "djf-snow-avgnds-ge050ti", "djf-snow-avgnds-ge050ti_attributes",
              "djf-snow-avgnds-ge100ti", "djf-snow-avgnds-ge100ti_attributes",
              "djf-snow-normal", "djf-snow-normal_attributes",
              "djf-snwd-avgnds-ge001wi", "djf-snwd-avgnds-ge001wi_attributes",
              "djf-snwd-avgnds-ge003wi", "djf-snwd-avgnds-ge003wi_attributes",
              "djf-snwd-avgnds-ge005wi", "djf-snwd-avgnds-ge005wi_attributes",
              "djf-snwd-avgnds-ge010wi", "djf-snwd-avgnds-ge010wi_attributes",
              "jja-prcp-avgnds-ge001hi", "jja-prcp-avgnds-ge001hi_attributes",
              "jja-prcp-avgnds-ge010hi", "jja-prcp-avgnds-ge010hi_attributes",
              "jja-prcp-avgnds-ge050hi", "jja-prcp-avgnds-ge050hi_attributes",
              "jja-prcp-avgnds-ge100hi", "jja-prcp-avgnds-ge100hi_attributes",
              "jja-prcp-normal", "jja-prcp-normal_attributes",
              "jja-snow-avgnds-ge001ti", "jja-snow-avgnds-ge001ti_attributes",
              "jja-snow-avgnds-ge010ti", "jja-snow-avgnds-ge010ti_attributes",
              "jja-snow-avgnds-ge030ti", "jja-snow-avgnds-ge030ti_attributes",
              "jja-snow-avgnds-ge050ti", "jja-snow-avgnds-ge050ti_attributes",
              "jja-snow-avgnds-ge100ti", "jja-snow-avgnds-ge100ti_attributes",
              "jja-snow-normal", "jja-snow-normal_attributes",
              "jja-snwd-avgnds-ge001wi", "jja-snwd-avgnds-ge001wi_attributes",
              "jja-snwd-avgnds-ge003wi", "jja-snwd-avgnds-ge003wi_attributes",
              "jja-snwd-avgnds-ge005wi", "jja-snwd-avgnds-ge005wi_attributes",
              "jja-snwd-avgnds-ge010wi", "jja-snwd-avgnds-ge010wi_attributes",
              "mam-prcp-normal", "mam-prcp-normal_attributes",
              "mam-snow-normal", "mam-snow-normal_attributes",
              "mam-snwd-avgnds-ge005wi", "mam-snwd-avgnds-ge005wi_attributes",
              "son-prcp-avgnds-ge001hi", "son-prcp-avgnds-ge001hi_attributes",
              "son-prcp-avgnds-ge010hi", "son-prcp-avgnds-ge010hi_attributes",
              "son-prcp-avgnds-ge050hi", "son-prcp-avgnds-ge050hi_attributes",
              "son-prcp-avgnds-ge100hi", "son-prcp-avgnds-ge100hi_attributes",
              "son-prcp-normal", "son-prcp-normal_attributes",
              "son-snow-avgnds-ge001ti", "son-snow-avgnds-ge001ti_attributes",
              "son-snow-avgnds-ge010ti", "son-snow-avgnds-ge010ti_attributes",
              "son-snow-avgnds-ge030ti", "son-snow-avgnds-ge030ti_attributes",
              "son-snow-avgnds-ge050ti", "son-snow-avgnds-ge050ti_attributes",
              "son-snow-avgnds-ge100ti", "son-snow-avgnds-ge100ti_attributes",
              "son-snow-normal", "son-snow-normal_attributes",
              "son-snwd-avgnds-ge001wi", "son-snwd-avgnds-ge001wi_attributes",
              "son-snwd-avgnds-ge003wi", "son-snwd-avgnds-ge003wi_attributes",
              "son-snwd-avgnds-ge005wi", "son-snwd-avgnds-ge005wi_attributes",
              "son-snwd-avgnds-ge010wi", "son-snwd-avgnds-ge010wi_attributes" ]
          DATA_DTYPE: >-
            { "station": "str", "date": "str",
              "latitude": "float64", "longitude": "float64",
              "elevation": "float64", "name": "str",
              "ann-prcp-avgnds-ge001hi": "str", "ann-prcp-avgnds-ge001hi_attributes": "str",
              "ann-prcp-avgnds-ge010hi": "str", "ann-prcp-avgnds-ge010hi_attributes": "str",
              "ann-prcp-avgnds-ge050hi": "str", "ann-prcp-avgnds-ge050hi_attributes": "str",
              "ann-prcp-avgnds-ge100hi": "str", "ann-prcp-avgnds-ge100hi_attributes": "str",
              "ann-prcp-normal": "str", "ann-prcp-normal_attributes": "str",
              "ann-snow-avgnds-ge001ti": "str", "ann-snow-avgnds-ge001ti_attributes": "str",
              "ann-snow-avgnds-ge010ti": "str", "ann-snow-avgnds-ge010ti_attributes": "str",
              "ann-snow-avgnds-ge030ti": "str", "ann-snow-avgnds-ge030ti_attributes": "str",
              "ann-snow-avgnds-ge050ti": "str", "ann-snow-avgnds-ge050ti_attributes": "str",
              "ann-snow-avgnds-ge100ti": "str", "ann-snow-avgnds-ge100ti_attributes": "str",
              "ann-snow-normal": "str", "ann-snow-normal_attributes": "str",
              "djf-prcp-avgnds-ge001hi": "str", "djf-prcp-avgnds-ge001hi_attributes": "str",
              "djf-prcp-avgnds-ge010hi": "str", "djf-prcp-avgnds-ge010hi_attributes": "str",
              "djf-prcp-avgnds-ge050hi": "str", "djf-prcp-avgnds-ge050hi_attributes": "str",
              "djf-prcp-avgnds-ge100hi": "str", "djf-prcp-avgnds-ge100hi_attributes": "str",
              "djf-prcp-normal": "str", "djf-prcp-normal_attributes": "str",
              "djf-snow-avgnds-ge001ti": "str", "djf-snow-avgnds-ge001ti_attributes": "str",
              "djf-snow-avgnds-ge010ti": "str", "djf-snow-avgnds-ge010ti_attributes": "str",
              "djf-snow-avgnds-ge030ti": "str", "djf-snow-avgnds-ge030ti_attributes": "str",
              "djf-snow-avgnds-ge050ti": "str", "djf-snow-avgnds-ge050ti_attributes": "str",
              "djf-snow-avgnds-ge100ti": "str", "djf-snow-avgnds-ge100ti_attributes": "str",
              "djf-snow-normal": "str", "djf-snow-normal_attributes": "str",
              "djf-snwd-avgnds-ge001wi": "str", "djf-snwd-avgnds-ge001wi_attributes": "str",
              "djf-snwd-avgnds-ge003wi": "str", "djf-snwd-avgnds-ge003wi_attributes": "str",
              "djf-snwd-avgnds-ge005wi": "str", "djf-snwd-avgnds-ge005wi_attributes": "str",
              "djf-snwd-avgnds-ge010wi": "str", "djf-snwd-avgnds-ge010wi_attributes": "str",
              "jja-prcp-avgnds-ge001hi": "str", "jja-prcp-avgnds-ge001hi_attributes": "str",
              "jja-prcp-avgnds-ge010hi": "str", "jja-prcp-avgnds-ge010hi_attributes": "str",
              "jja-prcp-avgnds-ge050hi": "str", "jja-prcp-avgnds-ge050hi_attributes": "str",
              "jja-prcp-avgnds-ge100hi": "str", "jja-prcp-avgnds-ge100hi_attributes": "str",
              "jja-prcp-normal": "str", "jja-prcp-normal_attributes": "str",
              "jja-snow-avgnds-ge001ti": "str", "jja-snow-avgnds-ge001ti_attributes": "str",
              "jja-snow-avgnds-ge010ti": "str", "jja-snow-avgnds-ge010ti_attributes": "str",
              "jja-snow-avgnds-ge030ti": "str", "jja-snow-avgnds-ge030ti_attributes": "str",
              "jja-snow-avgnds-ge050ti": "str", "jja-snow-avgnds-ge050ti_attributes": "str",
              "jja-snow-avgnds-ge100ti": "str", "jja-snow-avgnds-ge100ti_attributes": "str",
              "jja-snow-normal": "str", "jja-snow-normal_attributes": "str",
              "jja-snwd-avgnds-ge001wi": "str", "jja-snwd-avgnds-ge001wi_attributes": "str",
              "jja-snwd-avgnds-ge003wi": "str", "jja-snwd-avgnds-ge003wi_attributes": "str",
              "jja-snwd-avgnds-ge005wi": "str", "jja-snwd-avgnds-ge005wi_attributes": "str",
              "jja-snwd-avgnds-ge010wi": "str", "jja-snwd-avgnds-ge010wi_attributes": "str",
              "mam-prcp-normal": "str", "mam-prcp-normal_attributes": "str",
              "mam-snow-normal": "str", "mam-snow-normal_attributes": "str",
              "mam-snwd-avgnds-ge005wi": "str", "mam-snwd-avgnds-ge005wi_attributes": "str",
              "son-prcp-avgnds-ge001hi": "str", "son-prcp-avgnds-ge001hi_attributes": "str",
              "son-prcp-avgnds-ge010hi": "str", "son-prcp-avgnds-ge010hi_attributes": "str",
              "son-prcp-avgnds-ge050hi": "str", "son-prcp-avgnds-ge050hi_attributes": "str",
              "son-prcp-avgnds-ge100hi": "str", "son-prcp-avgnds-ge100hi_attributes": "str",
              "son-prcp-normal": "str", "son-prcp-normal_attributes": "str",
              "son-snow-avgnds-ge001ti": "str", "son-snow-avgnds-ge001ti_attributes": "str",
              "son-snow-avgnds-ge010ti": "str", "son-snow-avgnds-ge010ti_attributes": "str",
              "son-snow-avgnds-ge030ti": "str", "son-snow-avgnds-ge030ti_attributes": "str",
              "son-snow-avgnds-ge050ti": "str", "son-snow-avgnds-ge050ti_attributes": "str",
              "son-snow-avgnds-ge100ti": "str", "son-snow-avgnds-ge100ti_attributes": "str",
              "son-snow-normal": "str", "son-snow-normal_attributes": "str",
              "son-snwd-avgnds-ge001wi": "str", "son-snwd-avgnds-ge001wi_attributes": "str",
              "son-snwd-avgnds-ge003wi": "str", "son-snwd-avgnds-ge003wi_attributes": "str",
              "son-snwd-avgnds-ge005wi": "str", "son-snwd-avgnds-ge005wi_attributes": "str",
              "son-snwd-avgnds-ge010wi": "str", "son-snwd-avgnds-ge010wi_attributes": "str" ]
          INT_COL_LIST: >-
            [ "ann-prcp-avgnds-ge001hi",
              "ann-prcp-avgnds-ge010hi",
              "ann-prcp-avgnds-ge050hi",
              "ann-prcp-avgnds-ge100hi",
              "ann-prcp-normal",
              "ann-snow-avgnds-ge001ti",
              "ann-snow-avgnds-ge010ti",
              "ann-snow-avgnds-ge030ti",
              "ann-snow-avgnds-ge050ti",
              "ann-snow-avgnds-ge100ti",
              "ann-snow-normal",
              "djf-prcp-avgnds-ge001hi",
              "djf-prcp-avgnds-ge010hi",
              "djf-prcp-avgnds-ge050hi",
              "djf-prcp-avgnds-ge100hi",
              "djf-prcp-normal",
              "djf-snow-avgnds-ge001ti",
              "djf-snow-avgnds-ge010ti",
              "djf-snow-avgnds-ge030ti",
              "djf-snow-avgnds-ge050ti",
              "djf-snow-avgnds-ge100ti",
              "djf-snow-normal",
              "djf-snwd-avgnds-ge001wi",
              "djf-snwd-avgnds-ge003wi",
              "djf-snwd-avgnds-ge005wi",
              "djf-snwd-avgnds-ge010wi",
              "jja-prcp-avgnds-ge001hi",
              "jja-prcp-avgnds-ge010hi",
              "jja-prcp-avgnds-ge050hi",
              "jja-prcp-avgnds-ge100hi",
              "jja-prcp-normal",
              "jja-snow-avgnds-ge001ti",
              "jja-snow-avgnds-ge010ti",
              "jja-snow-avgnds-ge030ti",
              "jja-snow-avgnds-ge050ti",
              "jja-snow-avgnds-ge100ti",
              "jja-snow-normal",
              "jja-snwd-avgnds-ge001wi",
              "jja-snwd-avgnds-ge003wi",
              "jja-snwd-avgnds-ge005wi",
              "jja-snwd-avgnds-ge010wi",
              "mam-prcp-normal",
              "mam-snow-normal",
              "mam-snwd-avgnds-ge005wi",
              "son-prcp-avgnds-ge001hi",
              "son-prcp-avgnds-ge010hi",
              "son-prcp-avgnds-ge050hi",
              "son-prcp-avgnds-ge100hi",
              "son-prcp-normal",
              "son-snow-avgnds-ge001ti",
              "son-snow-avgnds-ge010ti",
              "son-snow-avgnds-ge030ti",
              "son-snow-avgnds-ge050ti",
              "son-snow-avgnds-ge100ti",
              "son-snow-normal",
              "son-snwd-avgnds-ge001wi",
              "son-snwd-avgnds-ge003wi",
              "son-snwd-avgnds-ge005wi",
              "son-snwd-avgnds-ge010wi" ]
        resources:
          request_memory: "12G"
          request_cpu: "1"
          request_ephemeral_storage: "16G"
    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: us-climate-normals-annualseasonal

  graph_paths:
    - "create_cluster >> annualseasonal_load >> delete_cluster"
