# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: cbsa_2019_1yr
    description: "CBSA 2019 1 year report table"

dag:
  airflow_version: 2
  initialize:
    dag_id: census_bureau_acs
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2021-03-01"
    max_active_runs: 1
    schedule_interval: "@once"
    catchup: False
    default_view: graph

  tasks:
    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: census_bureau_acs
          initial_node_count: 2
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-standard-16
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "cbsa_2019_1yr_transform_csv"
        startup_timeout_seconds: 600
        name: "cbsa_2019_1yr"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: census_bureau_acs
        namespace: "default"
        image_pull_policy: "Always"
        image: "{{ var.json.census_bureau_acs.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.source_url }}"
          TARGET_FILE: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.target_file }}"
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.dataset_id }}"
          TABLE_ID: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.destination_table }}"
          SCHEMA_PATH: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.schema_path }}"
          PIPELINE_NAME: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.pipeline_name }}"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.target_gcs_path }}"
          YEAR_REPORT: "1"
          API_NAMING_CONVENTION: "metropolitan%20statistical%20area/micropolitan%20statistical%20area"
          GEOGRAPHY: "cbsa"
          REPORT_LEVEL: "national_level"
          GROUP_ID_FILE: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.group_id_file }}"
          STATE_CODE_FILE: "{{ var.json.census_bureau_acs.cbsa_2019_1yr.state_code_file }}"
          CONCAT_COL_LIST: >-
            [
              "combined_statistical_area"
            ]
          RENAME_MAPPINGS_LIST: >-
            {
              "0":"name", 
              "1":"KPI_Value", 
              "2":"combined_statistical_area"
            }
          INPUT_CSV_HEADERS: >-
            [
              "geo_id",
              "aggregate_travel_time_to_work",
              "amerindian_including_hispanic",
              "amerindian_pop",
              "armed_forces",
              "asian_including_hispanic",
              "asian_male_45_54",
              "asian_male_55_64",
              "asian_pop",
							"associates_degree",
							"bachelors_degree",
							"bachelors_degree_2",
							"bachelors_degree_or_higher_25_64",
							"black_including_hispanic",
							"black_male_45_54",
							"black_male_55_64",
							"black_pop",
							"children",
							"children_in_single_female_hh",
							"civilian_labor_force",
							"commute_10_14_mins",
							"commute_15_19_mins",
							"commute_20_24_mins",
							"commute_25_29_mins",
							"commute_30_34_mins",
							"commute_35_39_mins",
							"commute_35_44_mins",
							"commute_40_44_mins",
							"commute_45_59_mins",
							"commute_5_9_mins",
							"commute_60_89_mins",
							"commute_60_more_mins",
							"commute_90_more_mins",
							"commute_less_10_mins",
							"commuters_16_over",
							"commuters_by_bus",
							"commuters_by_car_truck_van",
							"commuters_by_carpool",
							"commuters_by_public_transportation",
							"commuters_by_subway_or_elevated",
							"commuters_drove_alone",
							"different_house_year_ago_different_city",
							"different_house_year_ago_same_city",
							"dwellings_10_to_19_units",
							"dwellings_1_units_attached",
							"dwellings_1_units_detached",
							"dwellings_20_to_49_units",
							"dwellings_2_units",
							"dwellings_3_to_4_units",
							"dwellings_50_or_more_units",
							"dwellings_5_to_9_units",
							"employed_agriculture_forestry_fishing_hunting_mining",
							"employed_arts_entertainment_recreation_accommodation_food",
							"employed_construction",
							"employed_education_health_social",
							"employed_finance_insurance_real_estate",
							"employed_information",
							"employed_manufacturing",
							"employed_other_services_not_public_admin",
							"employed_pop",
							"employed_public_administration",
							"employed_retail_trade",
							"employed_science_management_admin_waste",
							"employed_transportation_warehousing_utilities",
							"employed_wholesale_trade",
							"families_with_young_children",
							"family_households",
							"father_in_labor_force_one_parent_families_with_young_children",
							"father_one_parent_families_with_young_children",
							"female_10_to_14",
							"female_15_to_17",
							"female_18_to_19",
							"female_20",
							"female_21",
							"female_22_to_24",
							"female_25_to_29",
							"female_30_to_34",
							"female_35_to_39",
							"female_40_to_44",
							"female_45_to_49",
							"female_50_to_54",
							"female_55_to_59",
							"female_5_to_9",
							"female_60_to_61",
							"female_62_to_64",
							"female_65_to_66",
							"female_67_to_69",
							"female_70_to_74",
							"female_75_to_79",
							"female_80_to_84",
							"female_85_and_over",
							"female_female_households",
							"female_pop",
							"female_under_5",
							"four_more_cars",
							"gini_index",
							"graduate_professional_degree",
							"group_quarters",
							"high_school_diploma",
							"high_school_including_ged",
							"hispanic_any_race",
							"hispanic_male_45_54",
							"hispanic_male_55_64",
							"hispanic_pop",
							"households",
							"households_public_asst_or_food_stamps",
							"households_retirement_income",
							"housing_built_1939_or_earlier",
							"housing_built_2000_to_2004",
							"housing_built_2005_or_later",
							"housing_units",
							"housing_units_renter_occupied",
							"in_grades_1_to_4",
							"in_grades_5_to_8",
							"in_grades_9_to_12",
							"in_school",
							"in_undergrad_college",
							"income_100000_124999",
							"income_10000_14999",
							"income_125000_149999",
							"income_150000_199999",
							"income_15000_19999",
							"income_200000_or_more",
							"income_20000_24999",
							"income_25000_29999",
							"income_30000_34999",
							"income_35000_39999",
							"income_40000_44999",
							"income_45000_49999",
							"income_50000_59999",
							"income_60000_74999",
							"income_75000_99999",
							"income_less_10000",
							"income_per_capita",
							"less_one_year_college",
							"less_than_high_school_graduate",
							"male_10_to_14",
							"male_15_to_17",
							"male_18_to_19",
							"male_20",
							"male_21",
							"male_22_to_24",
							"male_25_to_29",
							"male_30_to_34",
							"male_35_to_39",
							"male_40_to_44",
							"male_45_64_associates_degree",
							"male_45_64_bachelors_degree",
							"male_45_64_grade_9_12",
							"male_45_64_graduate_degree",
							"male_45_64_high_school",
							"male_45_64_less_than_9_grade",
							"male_45_64_some_college",
							"male_45_to_49",
							"male_45_to_64",
							"male_50_to_54",
							"male_55_to_59",
							"male_5_to_9",
							"male_60_to_61",
							"male_62_to_64",
							"male_65_to_66",
							"male_67_to_69",
							"male_70_to_74",
							"male_75_to_79",
							"male_80_to_84",
							"male_85_and_over",
							"male_male_households",
							"male_pop",
							"male_under_5",
							"management_business_sci_arts_employed",
							"married_households",
							"masters_degree",
							"median_age",
							"median_income",
							"median_rent",
							"median_year_structure_built",
							"million_dollar_housing_units",
							"mobile_homes",
							"mortgaged_housing_units",
							"no_car",
							"no_cars",
							"nonfamily_households",
							"not_hispanic_pop",
							"not_in_labor_force",
							"not_us_citizen_pop",
							"occupation_management_arts",
							"occupation_natural_resources_construction_maintenance",
							"occupation_production_transportation_material",
							"occupation_sales_office",
							"occupation_services",
							"occupied_housing_units",
							"one_car",
							"one_parent_families_with_young_children",
							"one_year_more_college",
							"other_race_pop",
							"owner_occupied_housing_units",
							"owner_occupied_housing_units_lower_value_quartile",
							"owner_occupied_housing_units_median_value",
							"owner_occupied_housing_units_upper_value_quartile",
							"percent_income_spent_on_rent",
							"pop_16_over",
							"pop_25_64",
							"pop_25_years_over",
							"pop_5_years_over",
							"pop_determined_poverty_status",
							"pop_in_labor_force",
							"population_1_year_and_over",
							"population_3_years_over",
							"poverty",
							"rent_10_to_15_percent",
							"rent_15_to_20_percent",
							"rent_20_to_25_percent",
							"rent_25_to_30_percent",
							"rent_30_to_35_percent",
							"rent_35_to_40_percent",
							"rent_40_to_50_percent",
							"rent_burden_not_computed",
							"rent_over_50_percent",
							"rent_under_10_percent",
							"renter_occupied_housing_units_paying_cash_median_gross_rent",
							"sales_office_employed",
							"some_college_and_associates_degree",
							"speak_only_english_at_home",
							"speak_spanish_at_home",
							"speak_spanish_at_home_low_english",
							"three_cars",
							"total_pop",
							"two_cars",
							"two_or_more_races_pop",
							"two_parent_families_with_young_children",
							"two_parents_father_in_labor_force_families_with_young_children",
							"two_parents_in_labor_force_families_with_young_children",
							"two_parents_mother_in_labor_force_families_with_young_children",
							"two_parents_not_in_labor_force_families_with_young_children",
							"unemployed_pop",
							"vacant_housing_units",
							"vacant_housing_units_for_rent",
							"vacant_housing_units_for_sale",
							"walked_to_work",
							"white_including_hispanic",
							"white_male_45_54",
							"white_male_55_64",
							"white_pop",
							"worked_at_home",
							"workers_16_and_over"
            ]
        resources:
          request_ephemeral_storage: "8G"
          limit_cpu: "3"

  graph_paths:
    - "create_cluster >> [ cbsa_2019_1yr_transform_csv ] >> delete_cluster"
