# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: "film_locations"
    description: "If you love movies, and you love San Francisco, you're bound to love this -- a listing of filming locations of movies shot in San Francisco starting from 1924. You'll find the titles, locations, fun facts, names of the director, writer, actors, and studio for most of these films."

dag:
  airflow_version: 2
  initialize:
    dag_id: film_locations
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:

    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: san-francisco-bikeshare--film-loc
          initial_node_count: 1
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-small
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform

    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"

      args:

        task_id: "transform_csv"
        name: "film_locations"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: san-francisco-bikeshare--film-loc
        namespace: "default"

        image_pull_policy: "Always"
        image: "{{ var.json.san_francisco_film_locations.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: "https://data.sfgov.org/api/views/yitu-d5am/rows.csv"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          CHUNKSIZE: "750000"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/san_francisco_film_locations/film_locations/data_output.csv"
        resources:
          limit_memory: "8G"
          limit_cpu: "3"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

      args:
        task_id: "load_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/san_francisco_film_locations/film_locations/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "san_francisco_film_locations.film_locations"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - "name": "title"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "release_year"
            "type": "INTEGER"
            "description": ""
            "mode": "NULLABLE"
          - "name": "locations"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "fun_facts"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "production_company"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "distributor"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "director"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "writer"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "actor_1"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "actor_2"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"
          - "name": "actor_3"
            "type": "STRING"
            "description": ""
            "mode": "NULLABLE"

    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: san-francisco-bikeshare--film-loc

  graph_paths:
    - "create_cluster >> transform_csv >> load_to_bq >> delete_cluster"
