# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  # A list of GCP resources that are unique and specific to your pipeline.
  #
  # The currently supported resources are shown below. Use only the resources
  # needed by your pipeline, and delete the rest of the examples.
  #
  # We will keep adding to the list below to support more Google Cloud resources
  # over time. If a resource you need isn't supported, please file an issue on
  # the repository.

  - type: bigquery_table
    # A Google BigQuery table to store your data. Requires a `bigquery_dataset`
    # to be specified in the config (i.e. `dataset.yaml) for the dataset that
    # this pipeline belongs in.
    #
    # Required Properties:
    #   table_id
    table_id: iris

dag:
  # The DAG acronym stands for directed acyclic graph. This block represents
  # your data pipeline along with every property and configuration it needs to
  # onboard your data.
  initialize:
    dag_id: iris
    default_args:
      owner: "Google"

      # When set to True, keeps a task from getting triggered if the previous schedule for the task hasn’t succeeded
      depends_on_past: False
      start_date: '2021-05-01'
    max_active_runs: 1
    schedule_interval: "@hourly"  # run once a week at Sunday 12am
    catchup: False
    default_view: graph

  tasks:
    # This is where you specify the tasks (a.k.a. processes) that your data
    # pipeline will run to onboard the data.
    #
    # As the examples below will show, every task must be represented by an
    # Airflow operator. The list of suported operators are listed in
    #
    #   scripts/dag_imports.json
    #
    # If an operator you need isn't supported, please file an issue on the
    # repository.
    #
    # Use the YAML list syntax in this block to specify every task for your
    # pipeline.

    - operator: "BashOperator"
      description: ""
      args:
        task_id: "download_csv_file"
        bash_command: |
          mkdir -p $airflow_data_folder/ml_datasets/iris
          curl -o $airflow_data_folder/ml_dataset/iris/data-source-{{ ds }}.csv -L $csv_source_url
        env:
          csv_source_url: "https://www.openml.org/data/get_csv/61/dataset_61_iris.csv"
          airflow_data_folder: "{{ var.json.shared.airflow_data_folder }}"

    - operator: "BashOperator"
      # Task description
      description: "Run a custom Python script"

      args:
        # Arguments supported by this operator:
        # https://airflow.apache.org/docs/apache-airflow/1.10.14/howto/operator/bash.html

        task_id: "transform_csv"
        bash_command: |
          SOURCE_CSV=$airflow_data_folder/ml_dataset/iris/data-source-{{ ds }}.csv TARGET_CSV=$airflow_data_folder/ml_dataset/iris/transformed-data-{{ ds }}.csv python $airflow_home/dags/$dataset/$pipeline/custom/transform_csv.py
        env:
          airflow_home: "{{ var.json.shared.airflow_home }}"
          airflow_data_folder: "{{ var.json.shared.airflow_data_folder }}"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      # Initializes GCS to BQ task for the DAG. This operator is used to load a
      # CSV file from GCS into a BigQuery table.

      # Task description
      description: "Task to load CSV data to a BigQuery table"

      args:
        # Arguments supported by this operator:
        # http://airflow.apache.org/docs/apache-airflow/1.10.14/howto/operator/gcp/gcs.html#googlecloudstoragetobigqueryoperator

        task_id: "load_to_bq"

        # The GCS bucket where the CSV file is located in.
        bucket: "{{ var.json.shared.composer_bucket }}"

        # The GCS object path for the CSV file
        source_objects: ["data/ml_datasets/iris/transformed-data-{{ ds }}.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "ml_datasets.iris"

        # Use this if your CSV file contains a header row
        skip_leading_rows: 1

        # How to write data to the table: overwrite, append, or write if empty
        # See https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/WriteDisposition
        write_disposition: "WRITE_TRUNCATE"

        # The BigQuery table schema based on the CSV file. For more info, see
        # https://cloud.google.com/bigquery/docs/schemas.
        # Always use snake_case and lowercase for column names, and be explicit,
        # i.e. specify modes for all columns.
        schema_fields:
          - name: sepal_length
            type: float
            description: ''
            mode: nullable
          - name: sepal_width
            type: float
            description: ''
            mode: nullable
          - name: petal_length
            type: float
            description: ''
            mode: nullable
          - name: petal_width
            type: float
            description: ''
            mode: nullable
          - name: species
            type: string
            description: ''
            mode: nullable

  graph_paths:
    # This is where you specify the relationships (i.e. directed paths/edges)
    # among the tasks specified above. Use the bitshift operator to define the
    # relationships and the `task_id` value above to represent tasks.
    #
    # For more info, see
    # https://airflow.apache.org/docs/apache-airflow/stable/tutorial.html#setting-up-dependencies
    - "download_csv_file >> transform_csv >> load_to_bq"
