# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: 311_service_requests
    description: "austin 311 service requests"

dag:
  airflow_version: 2
  initialize:
    dag_id: 311_service_requests
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "311_service_requests_transform_csv"
        image_pull_policy: "Always"
        name: "austin"
        namespace: "default"
        image: "{{ var.json.austin_311.container_registry.run_csv_transform_kub }}"
        env_vars:
          PIPELINE_NAME: "Austin 311 Service Requests By Year"
          SOURCE_URL: "https://data.austintexas.gov/api/views/xwdj-i9he/rows.csv"
          CHUNKSIZE: "750000"
          SOURCE_FILE: "files/data_austin_311_service_requests.csv"
          TARGET_FILE: "files/data_output_austin_311_service_requests.csv"
          TARGET_GCS_BUCKET: "{{ var.json.shared.composer_bucket }}"
          TARGET_GCS_PATH: "data/austin/311_service_requests/data_output.csv"
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "austin_311"
          DESTINATION_TABLE: "311_service_requests"
          SCHEMA_PATH: "data/austin/schema/austin_311_service_requests_schema.json"
          RENAME_HEADERS_LIST: >-
            {
              "Service Request (SR) Number": "unique_key",
              "SR Type Code": "complaint_type",
              "SR Description": "complaint_description",
              "Owning Department": "owning_department",
              "Method Received": "source",
              "SR Status": "status",
              "Status Change Date": "status_change_date",
              "Created Date": "created_date",
              "Last Update Date": "last_update_date",
              "Close Date": "close_date",
              "SR Location": "incident_address",
              "Street Number": "street_number",
              "Street Name": "street_name",
              "City": "city",
              "Zip Code": "incident_zip",
              "County": "county",
              "State Plane X Coordinate": "state_plane_x_coordinate",
              "State Plane Y Coordinate": "state_plane_y_coordinate",
              "Latitude Coordinate": "latitude",
              "Longitude Coordinate": "longitude",
              "(Latitude.Longitude)": "location",
              "Council District": "council_district_code",
              "Map Page": "map_page",
              "Map Tile": "map_tile"
            }
          INT_COLS_LIST: >-
            [
              "council_district_code"
            ]
          DATE_FORMAT_LIST: >-
            {
              "status_change_date": "%Y-%m-%d %H:%M:%S",
              "created_date": "%Y-%m-%d %H:%M:%S",
              "last_update_date": "%Y-%m-%d %H:%M:%S",
              "close_date": "%Y-%m-%d %H:%M:%S"
            }
        resources:
          request_memory: "10G"
          request_cpu: "2"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

  graph_paths:
    - "austin_311_service_requests_transform_csv"
