# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: 311_service_requests
    description: "austin 311 service requests"

dag:
  airflow_version: 2
  initialize:
    dag_id: 311_service_requests
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "311_service_requests_transform_csv"
        image_pull_policy: "Always"
        name: "austin"
        namespace: "default"
        image: "{{ var.json.austin_311.container_registry.run_csv_transform_kub }}"
        env_vars:
          PIPELINE_NAME: "Austin 311 Service Requests By Year"
          SOURCE_URL: "https://data.austintexas.gov/api/views/xwdj-i9he/rows.csv"
          CHUNKSIZE: "750000"
          SOURCE_FILE: "files/data_austin_311_service_requests.csv"
          TARGET_FILE: "files/data_output_austin_311_service_requests.csv"
          TARGET_GCS_BUCKET: "{{ var.json.shared.composer_bucket }}"
          TARGET_GCS_PATH: "data/austin/311_service_requests/data_output.csv"
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "austin_311"
          DESTINATION_TABLE: "311_service_requests"
          SCHEMA_PATH: "data/austin/schema/austin_311_service_requests_schema.json"
          DATE_FORMAT_LIST: >-
            {
              "status_change_date": "%Y-%m-%d %H:%M:%S",
              "created_date": "%Y-%m-%d %H:%M:%S",
              "last_update_date": "%Y-%m-%d %H:%M:%S",
              "close_date": "%Y-%m-%d %H:%M:%S"
            }
          INT_COLS_LIST: >-
            [
              "council_district_code"
            ]
          REMOVE_NEWLINES_COLS_LIST: >-
            [
              "location"
            ]
          NULL_ROWS_LIST: >-
            [
              "unique_key"
            ]
          INPUT_CSV_HEADERS: >-
            [
              "Service Request (SR) Number",
              "SR Type Code",
              "SR Description",
              "Owning Department",
              "Method Received",
              "SR Status",
              "Status Change Date",
              "Created Date",
              "Last Update Date",
              "Close Date",
              "SR Location",
              "Street Number",
              "Street Name",
              "City",
              "Zip Code",
              "County",
              "State Plane X Coordinate",
              "State Plane Y Coordinate",
              "Latitude Coordinate",
              "Longitude Coordinate",
              "(Latitude.Longitude)",
              "Council District",
              "Map Page",
              "Map Tile"
            ]
          DATA_DTYPES: >-
            {
              "Service Request (SR) Number": "str",
              "SR Description": "str",
              "Method Received": "str",
              "SR Status": "str",
              "Status Change Date": "datetime64",
              "Created Date": "datetime64",
              "Last Update Date": "datetime64",
              "Close Date": "datetime64",
              "SR Location": "str",
              "Street Number": "str",
              "Street Name": "str",
              "City": "str",
              "Zip Code": "str",
              "County": "str",
              "State Plane X Coordinate": "float",
              "State Plane Y Coordinate": "float",
              "Latitude Coordinate": "Float",
              "Longitude Coordinate": "float",
              "(Latitude.Longitude)": "str",
              "Council District": "int",
              "Map Page": "str",
              "Map Tile": "str"
            }
          RENAME_HEADERS_LIST: >-
            {
              "Service Request (SR) Number": "unique_key",
              "SR Description": "complaint_description",
              "Method Received": "source",
              "SR Status": "status",
              "Status Change Date": "status_change_date",
              "Created Date": "created_date",
              "Last Update Date": "last_update_date",
              "Close Date": "close_date",
              "SR Location": "incident_address",
              "Street Number": "street_number",
              "Street Name": "street_name",
              "City": "city",
              "Zip Code": "incident_zip",
              "County": "county",
              "State Plane X Coordinate": "state_plane_x_coordinate",
              "State Plane Y Coordinate": "state_plane_y_coordinate",
              "Latitude Coordinate": "latitude",
              "Longitude Coordinate": "longitude",
              "(Latitude.Longitude)": "location",
              "Council District": "council_district_code",
              "Map Page": "map_page",
              "Map Tile": "map_tile"
            }
          REORDER_HEADERS_LIST: >-
            [
              "unique_key",
              "complaint_description",
              "source",
              "status",
              "status_change_date",
              "created_date",
              "last_update_date",
              "close_date",
              "incident_address",
              "street_number",
              "street_name",
              "city",
              "incident_zip",
              "county",
              "state_plane_x_coordinate",
              "state_plane_y_coordinate",
              "latitude",
              "longitude",
              "location",
              "council_district_code",
              "map_page",
              "map_tile"
            ]
        resources:
          request_memory: "10G"
          request_cpu: "2"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

  graph_paths:
    - "austin_311_service_requests_transform_csv"
