# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    # Required Properties:
    table_id: national_statistics_by_parent_income_percentile_gender_race

    # Description of the table
    description: "Race and Economic Opportunity Data Tables"

dag:

  airflow_version: 1

  initialize:
    dag_id: national_statistics_by_parent_income_percentile_gender_race
    default_args:
      owner: "Google"

      # When set to True, keeps a task from getting triggered if the previous schedule for the task hasn’t succeeded
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:

    - operator: "KubernetesPodOperator"

      # Task description
      description: "Run CSV transform within kubernetes pod"

      args:

        task_id: "national_statistics_transform_csv"
        startup_timeout_seconds: 600

        # The name of the pod in which the task will run. This will be used (plus a random suffix) to generate a pod id
        name: "race_and_economic_opportunity_national_statistics_by_parent_income_percentile_gender_race"

        # The namespace to run within Kubernetes. Always set its value to "default" because we follow the guideline that KubernetesPodOperator will only be used for very light workloads, i.e. use the Cloud Composer environment's resources without starving other pipelines.
        namespace: "default"

        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: cloud.google.com/gke-nodepool
                      operator: In
                      values:
                        - "pool-e2-standard-4"

        image_pull_policy: "Always"

        # Docker images will be built and pushed to GCR by default whenever the `scripts/generate_dag.py` is run. To skip building and pushing images, use the optional `--skip-builds` flag.
        image: "{{ var.json.race_and_economic_opportunity.container_registry.run_csv_transform_kub }}"

        # Set the environment variables you need initialized in the container. Use these as input variables for the script your container is expected to perform.
        env_vars:
          SOURCE_URL: "https://www2.census.gov/ces/opportunity/table_1.csv"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/race_and_economic_opportunity/national_statistics_by_parent_income_percentile_gender_race/data_output.csv"
          CSV_HEADERS: >-
           ["par_pctile","count_pooled","count_aian_pooled","count_asian_pooled","count_black_pooled","count_hisp_pooled","count_white_pooled","density_aian_pooled","density_asian_pooled","density_black_pooled","density_hisp_pooled","density_white_pooled","kfr_aian_pooled","kfr_asian_pooled","kfr_black_female","kfr_black_male","kfr_black_pooled","kfr_hisp_pooled","kfr_nativemom_aian_pooled","kfr_nativemom_asian_pooled","kfr_nativemom_black_pooled","kfr_nativemom_hisp_pooled","kfr_nativemom_white_pooled","kfr_pooled","kfr_white_female","kfr_white_male","kfr_white_pooled","kid_college_black_female","kid_college_black_male","kid_college_white_female","kid_college_white_male","kid_hours_black_female","kid_hours_black_male","kid_hours_white_female","kid_hours_white_male","kid_jail_black_female","kid_jail_black_male","kid_jail_white_female","kid_jail_white_male","kid_married_black_pooled","kid_married_white_pooled","kid_no_hs_black_female","kid_no_hs_black_male","kid_no_hs_white_female","kid_no_hs_white_male","kid_pos_hours_black_female","kid_pos_hours_black_male","kid_pos_hours_white_female","kid_pos_hours_white_male","kid_wage_rank_black_female","kid_wage_rank_black_male","kid_wage_rank_white_female","kid_wage_rank_white_male","kir_black_female","kir_black_male","kir_black_pooled","kir_white_female","kir_white_male","kir_white_pooled","kir_1par_black_male","kir_1par_white_male","kir_2par_black_male","kir_2par_white_male","kir_par_nohome_black_male","kir_par_nohome_white_male","spouse_rank_black_female","spouse_rank_black_male","spouse_rank_white_female","spouse_rank_white_male"]
          RENAME_MAPPINGS: >-
           {"par_pctile": "par_pctile","count_pooled": "count_pooled","count_aian_pooled": "count_aian_pooled": "count_aian_pooled","count_asian_pooled": "count_asian_pooled","count_black_pooled": "count_black_pooled","count_hisp_pooled": "count_hisp_pooled","count_white_pooled": "count_white_pooled","density_aian_pooled": "density_aian_pooled","density_asian_pooled": "density_asian_pooled","density_black_pooled": "density_black_pooled","density_hisp_pooled": "density_hisp_pooled","density_white_pooled": "density_white_pooled","kfr_aian_pooled": "kfr_aian_pooled","kfr_asian_pooled": "kfr_asian_pooled","kfr_black_female": "kfr_black_female","kfr_black_male": "kfr_black_male","kfr_black_pooled": "kfr_black_pooled","kfr_hisp_pooled": "kfr_hisp_pooled","kfr_nativemom_aian_pooled": "kfr_nativemom_aian_pooled","kfr_nativemom_asian_pooled": "kfr_nativemom_asian_pooled","kfr_nativemom_black_pooled": "kfr_nativemom_black_pooled","kfr_nativemom_hisp_pooled": "kfr_nativemom_hisp_pooled","kfr_nativemom_white_pooled": "kfr_nativemom_white_pooled","kfr_pooled": "kfr_pooled","kfr_white_female": "kfr_white_female","kfr_white_male": "kfr_white_male","kfr_white_pooled": "kfr_white_pooled","kid_college_black_female": "kid_college_black_female","kid_college_black_male": "kid_college_black_male","kid_college_white_female": "kid_college_white_female","kid_college_white_male": "kid_college_white_male","kid_hours_black_female": "kid_hours_black_female","kid_hours_black_male": "kid_hours_black_male","kid_hours_white_female": "kid_hours_white_female","kid_hours_white_male": "kid_hours_white_male","kid_jail_black_female": "kid_jail_black_female","kid_jail_black_male": "kid_jail_black_male","kid_jail_white_female": "kid_jail_white_female","kid_jail_white_male": "kid_jail_white_male","kid_married_black_pooled": "kid_married_black_pooled","kid_married_white_pooled": "kid_married_white_pooled","kid_no_hs_black_female": "kid_no_hs_black_female","kid_no_hs_black_male": "kid_no_hs_black_male","kid_no_hs_white_female": "kid_no_hs_white_female","kid_no_hs_white_male": "kid_no_hs_white_male","kid_pos_hours_black_female": "kid_pos_hours_black_female","kid_pos_hours_black_male": "kid_pos_hours_black_male","kid_pos_hours_white_female": "kid_pos_hours_white_female","kid_pos_hours_white_male": "kid_pos_hours_white_male","kid_wage_rank_black_female": "kid_wage_rank_black_female","kid_wage_rank_black_male": "kid_wage_rank_black_male","kid_wage_rank_white_female": "kid_wage_rank_white_female","kid_wage_rank_white_male": "kid_wage_rank_white_male,"kir_black_female": "kir_black_female,"kir_black_male": "kir_black_male","kir_black_pooled": "kir_black_pooled","kir_white_female": "kir_white_female","kir_white_male": "kir_white_male","kir_white_pooled ": "kir_white_pooled","kir_1par_black_male": "kir_1par_black_male","kir_1par_white_male": "kir_1par_white_male","kir_2par_black_male": "kir_2par_black_male","kir_2par_white_male": "kir_2par_white_male","kir_par_nohome_black_male": "kir_par_nohome_black_male","kir_par_nohome_white_male": "kir_par_nohome_white_male","spouse_rank_black_female": "spouse_rank_black_female","spouse_rank_black_male": "spouse_rank_black_male","spouse_rank_white_female": "spouse_rank_white_female","spouse_rank_white_male": "spouse_rank_white_male"}
          PIPELINE_NAME: "national_statistics_by_parent_income_percentile_gender_race"

        # Set resource limits for the pod here. For resource units in Kubernetes, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
        resources:
          limit_memory: "2G"
          limit_cpu: "1"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_national_statistics_to_bq"

        # The GCS bucket where the CSV file is located in.
        bucket: "{{ var.value.composer_bucket }}"

        # The GCS object path for the CSV file
        source_objects: ["data/race_and_economic_opportunity/national_statistics_by_parent_income_percentile_gender_race/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "race_and_economic_opportunity.national_statistics_by_parent_income_percentile_gender_race"

        # Use this if your CSV file contains a header row
        skip_leading_rows: 1

        # How to write data to the table: overwrite, append, or write if empty
        # See https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/WriteDisposition
        write_disposition: "WRITE_TRUNCATE"

        # The BigQuery table schema based on the CSV file. For more info, see
        # https://cloud.google.com/bigquery/docs/schemas.
        # Always use snake_case and lowercase for column names, and be explicit,
        # i.e. specify modes for all columns.
        # types: "INTEGER", "TIMESTAMP", "STRING"
        schema_fields:
          - name: "par_pctile"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "count_pooled"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "count_aian_pooled"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "count_asian_pooled"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "count_black_pooled"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "count_hisp_pooled"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "count_white_pooled"
            type: "INTEGER"
            mode: "NULLABLE"
          - name: "density_aian_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "density_asian_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "density_black_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "density_hisp_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "density_white_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_aian_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_asian_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_black_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_hisp_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_nativemom_aian_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_nativemom_asian_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_nativemom_black_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_nativemom_hisp_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_nativemom_white_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kfr_white_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_college_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_college_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_college_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_college_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_hours_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_hours_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_hours_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_hours_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_jail_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_jail_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_jail_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_jail_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_married_black_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_married_white_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_no_hs_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_no_hs_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_no_hs_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_no_hs_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_pos_hours_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_pos_hours_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_pos_hours_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_pos_hours_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_wage_rank_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_wage_rank_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_wage_rank_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kid_wage_rank_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_black_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_white_pooled"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_1par_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_1par_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_2par_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_2par_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_par_nohome_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "kir_par_nohome_white_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "spouse_rank_black_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "spouse_rank_black_male"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "spouse_rank_white_female"
            type: "FLOAT"
            mode: "NULLABLE"
          - name: "spouse_rank_white_male"
            type: "FLOAT"
            mode: "NULLABLE"

  graph_paths:
    - "national_statistics_transform_csv >> load_national_statistics_to_bq"
