# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: cycle_stations
    description: "This table consists live cycle hire updates(hourly) of london city."
  - type: bigquery_table
    table_id: cycle_trips
    description: "This table consists live cycle trips updates(hourly) of london city."

dag:
  airflow_version: 2
  initialize:
    dag_id: london_bicycles
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2021-03-01"
    max_active_runs: 1
    schedule_interval: "0 0 * * 6"
    catchup: False
    default_view: graph
  tasks:
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "stations_csv_transform"
        startup_timeout_seconds: 600
        name: "london_bicycle_stations"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.london_bicycles.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: >-
            {
              "stations": "https://tfl.gov.uk/tfl/syndication/feeds/cycle-hire/livecyclehireupdates.xml"
            }
          SOURCE_FILE: "./files/livecyclehireupdates.xml"
          REQUIRED_COLS: >-
            [
              "id",
              "installed",
              "lat",
              "locked",
              "long",
              "name",
              "nbBikes",
              "nbDocks",
              "nbEmptyDocks",
              "temporary",
              "terminalName",
              "installDate",
              "removalDate"
            ]
          RENAME_MAPPINGS: >-
            {
              "id": "id",
              "installed": "installed",
              "lat": "latitude",
              "locked": "locked",
              "long": "longitude",
              "name": "name",
              "nbBikes": "bikes_count",
              "nbDocks": "docks_count",
              "nbEmptyDocks": "nbEmptyDocks",
              "temporary": "temporary",
              "terminalName": "terminal_name",
              "installDate": "install_date",
              "removalDate": "removal_date"
            }
          DATE_COLS: >-
            [
              "installDate",
              "removalDate"
            ]
          INTEGER_COLS: >-
            [
              "id",
              "nbBikes",
              "nbDocks",
              "nbEmptyDocks",
              "terminalName"
            ]
          FLOAT_COLS: >-
            [
              "lat",
              "long"
            ]
          STRING_COLS: >-
            [
              "installed",
              "locked",
              "name",
              "temporary"
            ]
          OUTPUT_FILE: "./files/cycle_stations_data_output.csv"
          GCS_BUCKET: "{{ var.json.london_bicycles.storage_bucket }}"
          TARGET_GCS_PATH: "data/london_bicycles/cycle_stations_data_output.csv"
          PIPELINE: "London Cycle Stations Dataset"
        resources:
          limit_memory: "8G"
          limit_cpu: "1"
          request_ephemeral_storage: "10G"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_cycle_stations_to_bq"
        bucket: "{{ var.json.london_bicycles.storage_bucket }}"
        source_objects: ["data/london_bicycles/cycle_stations_data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "london_bicycles.cycle_stations"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - name: "id"
            type: "integer"
            mode: "nullable"
          - name: "installed"
            type: "boolean"
            mode: "nullable"
          - name: "latitude"
            type: "float"
            mode: "nullable"
          - name: "locked"
            type: "string"
            mode: "nullable"
          - name: "longitude"
            type: "float"
            mode: "nullable"
          - name: "name"
            type: "string"
            mode: "nullable"
          - name: "bikes_count"
            type: "integer"
            mode: "nullable"
          - name: "docks_count"
            type: "integer"
            mode: "nullable"
          - name: "nbEmptyDocks"
            type: "integer"
            mode: "nullable"
          - name: "temporary"
            type: "boolean"
            mode: "nullable"
          - name: "terminal_name"
            type: "string"
            mode: "nullable"
          - name: "install_date"
            type: "date"
            mode: "nullable"
          - name: "removal_date"
            type: "date"
            mode: "nullable"

    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "trips_csv_transform"
        startup_timeout_seconds: 600
        name: "london_bicycle_trips"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.london_bicycles.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: >-
            {
              "trips": "gs://london-cycling-data"
            }
          SOURCE_FILE: "./files/journey.csv"
          LOAD_START_DATE_FLOOR: "{{ var.json.london_bicycles.cycle_hire.load_start_date_floor }}"
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "london_bicycles"
          TABLE_ID: "cycle_hire"
          RENAME_MAPPINGS: >-
            {
              "Rental Id": "rental_id",
              "Duration_Seconds": "duration_str",
              "Duration": "duration_str",
              "Bike Id": "bike_id",
              "End Date": "end_date",
              "EndStation Id": "end_station_id",
              "End Station Id": "end_station_id",
              "EndStation Name": "end_station_name",
              "End Station Name": "end_station_name",
              "Start Date": "start_date",
              "StartStation Id": "start_station_id",
              "Start Station Id": "start_station_id",
              "StartStation Name": "start_station_name",
              "Start Station Name": "start_station_name",
              "Number": "rental_id",
              "Start date": "start_date",
              "Start station number": "start_station_id",
              "Start station": "start_station_name",
              "End date": "end_date",
              "End station number": "end_station_id",
              "End station": "end_station_name",
              "Bike number": "bike_id",
              "Bike model": "bike_model",
              "Total duration": "duration_str",
              "Total duration (ms)": "duration_ms"
            }
          OUTPUT_FILE: "./files/cycle_trips_data_output.csv"
          GCS_BUCKET: "{{ var.value.composer_bucket }}"
          SCHEMA_PATH: "data/london_bicycles/schema/cycle_hire_schema.json"
          DATA_DTYPES: >-
            {
              "rental_id": "int32",
              "duration_str": "int32",
              "duration_ms": "int32",
              "bike_id": "int32",
              "bike_model": "str",
              "end_date": "datetime64",
              "end_station_id": "int32",
              "end_station_name": "str",
              "start_date": "datetime64",
              "start_station_id": "int32",
              "start_station_name": "str",
              "end_station_logical_terminal": "int32",
              "start_station_logical_terminal": "int32",
              "end_station_priority_id": "int32"
            }
          OUTPUT_CSV_HEADERS: >-
            [
              "rental_id",
              "duration",
              "duration_ms",
              "bike_id",
              "bike_model",
              "end_date",
              "end_station_id",
              "end_station_name",
              "start_date",
              "start_station_id",
              "start_station_name",
              "end_station_logical_terminal",
              "start_station_logical_terminal",
              "end_station_priority_id"
            ]
          PIPELINE: "London Cycle Trips Dataset"
        resources:
          limit_memory: "8G"
          limit_cpu: "1"
          request_ephemeral_storage: "10G"

  graph_paths:
    - "stations_csv_transform >> load_cycle_stations_to_bq >> trips_csv_transform"
