# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# requestations under the License.

---
resources:


dag:
  airflow_version: 2
  initialize:
    dag_id: noaa_passive_bioacoustic
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2022-09-01"
    max_active_runs: 1
    schedule_interval: "@yearly"
    catchup: False
    default_view: graph

  tasks:
    - operator: "GoogleCloudStorageToGoogleCloudStorageOperator"
      description: "Copy objects from source bucket"
      args:
        task_id: "gcs_to_gcs"
        source_bucket: "{{ var.json.noaa_passive_bioacoustic.source_bucket }}"
        source_object: "{{ var.json.noaa_passive_bioacoustic.source_object }}"  
        destination_bucket: "{{ var.json.noaa_passive_bioacoustic.destination_bucket }}"
        destination_object: "{{ var.json.noaa_passive_bioacoustic.destination_object }}"
        move_object: False
        replace: False


    # - operator: "KubernetesPodOperator"
    #   description: "ETL within the kubernetes pod"
    #   args:
    #     task_id: "py_gcs_to_bq"
    #     startup_timeout_seconds: 1000
    #     name: "load_data"
    #     namespace: "composer"
    #     service_account_name: "datasets"
    #     image_pull_policy: "Always"
    #     image: "{{ var.json.open_buildings.container_registry.run_script_kub }}"
    #     env_vars:
    #       SOURCE_GCS_PATH: "{{ var.json.open_buildings.source_gcs_path }}"
    #       PROJECT_ID: "{{ var.value.gcp_project }}"
    #       DATASET_ID: "{{ var.json.open_buildings.dataset_id }}"
    #       GCS_BUCKET: "{{ var.value.composer_bucket }}"
    #       SCHEMA_FILEPATH: "schema.json"
    #     resources:
    #       request_memory: "2G"
    #       request_cpu: "1"
    #       request_ephemeral_storage: "10G"

  graph_paths:
    - "gcs_to_gcs"
