# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: "so2_hourly_summary"
    description: "epaspc"

dag:
  airflow_version: 2
  initialize:
    dag_id: so2_hourly_summary
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "0 12 * * *"
    catchup: False
    default_view: graph
  tasks:
    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: epa-hist-air-quality
          initial_node_count: 50
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-standard-16
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform
    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "transform_csv_and_load_data"
        startup_timeout_seconds: 600
        name: "load_data"
        namespace: "default"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: epa-hist-air-quality
        image_pull_policy: "Always"
        image: "{{ var.json.epa_historical_air_quality.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: "{{ var.json.epa_historical_air_quality.so2_hourly_summary.source_url }}"
          START_YEAR: "1990"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "{{ var.json.epa_historical_air_quality.dataset_id }}"
          TABLE_ID: "{{ var.json.epa_historical_air_quality.so2_hourly_summary.table_id }}"
          SCHEMA_PATH: "{{ var.json.epa_historical_air_quality.so2_hourly_summary.schema_path }}"
          CHUNKSIZE: "{{ var.json.epa_historical_air_quality.so2_hourly_summary.chunk_size }}"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "{{ var.json.epa_historical_air_quality.so2_hourly_summary.target_gcs_path }}"
          PIPELINE_NAME: "epa_historical_air_quality - so2_hourly_summary"
          INPUT_CSV_HEADERS: >-
            [ "state_code", "county_code", "site_num", "parameter_code", "poc",
              "latitude", "longitude", "datum", "parameter_name", "date_local",
              "time_local", "date_gmt", "time_gmt", "sample_measurement", "units_of_measure",
              "mdl", "uncertainty", "qualifier", "method_type", "method_code", "method_name",
              "state_name", "county_name", "date_of_last_change" ]
          DATA_DTYPES: >-
            { "state_code": "str", "county_code": "str", "site_num": "str", "parameter_code": "int32", "poc": "int32",
              "latitude": "float64", "longitude": "float64", "datum": "str", "parameter_name": "str", "date_local": "datetime64[ns]",
              "time_local": "str", "date_gmt": "datetime64[ns]", "time_gmt": "str", "sample_measurement": "float64", "units_of_measure": "str",
              "mdl": "float64", "uncertainty": "float64", "qualifier": "str", "method_type": "str", "method_code": "int32", "method_name": "str",
              "state_name": "str", "county_name": "str", "date_of_last_change": "datetime64[ns]" }
          OUTPUT_CSV_HEADERS: >-
            [ "state_code", "county_code", "site_num", "parameter_code", "poc",
              "latitude", "longitude", "datum", "parameter_name", "date_local",
              "time_local", "date_gmt", "time_gmt", "sample_measurement", "units_of_measure",
              "mdl", "uncertainty", "qualifier", "method_type", "method_code", "method_name",
              "state_name", "county_name", "date_of_last_change" ]
        resources:
          request_memory: "8G"
          request_cpu: "1"
          request_ephemeral_storage: "12G"
    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: epa-hist-air-quality
  graph_paths:
    - "create_cluster >> transform_csv_and_load_data >> delete_cluster"
