# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# requestations under the License.

---
resources:
  - type: bigquery_table
    table_id: dependencies
    description:

dag:
  airflow_version: 2
  initialize:
    dag_id: dependencies
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2022-11-15"
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:
    - operator: "BashOperator"
      description: "Fetch data gcs - gcs"
      args:
        task_id: "bash_gcs_to_gcs"
        bash_command: |
          gsutil cp -R gs://pdp-feeds-staging/Libraries/libraries-1.4.0-2018-12-22/dependencies-1.4.0-2018-12-22.csv gs://{{ var.value.composer_bucket }}/data/libraries_io/dependencies/dependencies.csv
          split -l 40000000 --additional-suffix=.csv /home/airflow/gcs/data/libraries_io/dependencies/dependencies.csv /home/airflow/gcs/data/libraries_io/dependencies/
          rm /home/airflow/gcs/data/libraries_io/dependencies/dependencies.csv

    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "transform_dependencies"
        startup_timeout_seconds: 600
        name: "dependencies"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.libraries_io.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          SOURCE_GCS_OBJECT: "data/libraries_io/dependencies/aa.csv"
          SOURCE_FILE: "files/dependencies.csv"
          TARGET_FILE: "files/data_dependencies.csv"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/libraries_io/dependencies/data_dependencies_1.csv"
          CHUNKSIZE: "100000"
          PIPELINE_NAME: "dependencies"
          RENAME_MAPPINGS: >-
            {"ID":"id","Platform":"platform","Project Name":"project_name","Project ID":"project_id","Version Number":"version_number",
            "Version ID":"version_id","Dependency Name":"dependency_name","Dependency Platform":"dependency_platform",
            "Dependency Kind":"dependency_kind","Optional Dependency":"optional_dependency",
            "Dependency Requirements":"dependency_requirements","Dependency Project ID":"dependency_project_id"}
          CSV_HEADERS: >-
            ["id","platform","project_name","project_id","version_number","version_id","dependency_name","dependency_platform",
            "dependency_kind","optional_dependency","dependency_requirements","dependency_project_id"]
        resources:
          request_memory: "4G"
          request_cpu: "1"
          request_ephemeral_storage: "10G"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_dependencies_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/libraries_io/dependencies/data_dependencies_1.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "libraries_io.dependencies"
        skip_leading_rows: 2
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - name: "id"
            type: "integer"
            description: "The unique primary key of the dependency in the Libraries.io database."
            mode: "nullable"
          - name: "platform"
            type: "string"
            description: "The name of the Package manager the dependency is available on."
            mode: "nullable"
          - name: "project_name"
            type: "string"
            description: "The name of the project the dependency belongs to."
            mode: "nullable"
          - name: "project_id"
            type: "integer"
            description: "The unique primary key of the project for this dependency in the Libraries.io database."
            mode: "nullable"
          - name: "version_number"
            type: "string"
            description: "The number of the version that the dependency belongs to."
            mode: "nullable"
          - name: "version_id"
            type: "integer"
            description: "The unique primary key of the version for this dependency in the Libraries.io database."
            mode: "nullable"
          - name: "dependency_name"
            type: "string"
            description: "The name of the project that the dependency specifies."
            mode: "nullable"
          - name: "dependency_platform"
            type: "string"
            description: "The name of the package manager that the project that the dependency specifies is available from (only different for Atom)."
            mode: "nullable"
          - name: "dependency_kind"
            type: "string"
            description: "The type of dependency, often declared for the phase of usage, e.g. runtime, test, development, build."
            mode: "nullable"
          - name: "optional_dependency"
            type: "string"
            description: "Is the dependency optional?."
            mode: "nullable"
          - name: "dependency_requirements"
            type: "string"
            description: "The version or range of versions that the dependency specifies, resolution of that to a particular version is package manager specific."
            mode: "nullable"
          - name: "dependency_project_id"
            type: "integer"
            description: "The unique primary key of the project for this dependency in the Libraries.io database."
            mode: "nullable"

    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "transform_dependencies_2"
        startup_timeout_seconds: 600
        name: "dependencies"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.libraries_io.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          SOURCE_GCS_OBJECT: "data/libraries_io/dependencies/ab.csv"
          SOURCE_FILE: "files/dependencies.csv"
          TARGET_FILE: "files/data_dependencies.csv"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/libraries_io/dependencies/data_dependencies_2.csv"
          CHUNKSIZE: "100000"
          PIPELINE_NAME: "dependencies"
          RENAME_MAPPINGS: >-
            {"ID":"id","Platform":"platform","Project Name":"project_name","Project ID":"project_id","Version Number":"version_number",
            "Version ID":"version_id","Dependency Name":"dependency_name","Dependency Platform":"dependency_platform",
            "Dependency Kind":"dependency_kind","Optional Dependency":"optional_dependency",
            "Dependency Requirements":"dependency_requirements","Dependency Project ID":"dependency_project_id"}
          CSV_HEADERS: >-
            ["id","platform","project_name","project_id","version_number","version_id","dependency_name","dependency_platform",
            "dependency_kind","optional_dependency","dependency_requirements","dependency_project_id"]
        resources:
          request_memory: "4G"
          request_cpu: "1"
          request_ephemeral_storage: "10G"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_dependencies_to_bq_2"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/libraries_io/dependencies/data_dependencies_2.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "libraries_io.dependencies"
        skip_leading_rows: 2
        allow_quoted_newlines: True
        write_disposition: "WRITE_APPEND"
        schema_fields:
          - name: "id"
            type: "integer"
            description: "The unique primary key of the dependency in the Libraries.io database."
            mode: "nullable"
          - name: "platform"
            type: "string"
            description: "The name of the Package manager the dependency is available on."
            mode: "nullable"
          - name: "project_name"
            type: "string"
            description: "The name of the project the dependency belongs to."
            mode: "nullable"
          - name: "project_id"
            type: "integer"
            description: "The unique primary key of the project for this dependency in the Libraries.io database."
            mode: "nullable"
          - name: "version_number"
            type: "string"
            description: "The number of the version that the dependency belongs to."
            mode: "nullable"
          - name: "version_id"
            type: "integer"
            description: "The unique primary key of the version for this dependency in the Libraries.io database."
            mode: "nullable"
          - name: "dependency_name"
            type: "string"
            description: "The name of the project that the dependency specifies."
            mode: "nullable"
          - name: "dependency_platform"
            type: "string"
            description: "The name of the package manager that the project that the dependency specifies is available from (only different for Atom)."
            mode: "nullable"
          - name: "dependency_kind"
            type: "string"
            description: "The type of dependency, often declared for the phase of usage, e.g. runtime, test, development, build."
            mode: "nullable"
          - name: "optional_dependency"
            type: "string"
            description: "Is the dependency optional?."
            mode: "nullable"
          - name: "dependency_requirements"
            type: "string"
            description: "The version or range of versions that the dependency specifies, resolution of that to a particular version is package manager specific."
            mode: "nullable"
          - name: "dependency_project_id"
            type: "integer"
            description: "The unique primary key of the project for this dependency in the Libraries.io database."
            mode: "nullable"

    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "transform_dependencies_3"
        startup_timeout_seconds: 600
        name: "dependencies"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.libraries_io.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          SOURCE_GCS_OBJECT: "data/libraries_io/dependencies/ac.csv"
          SOURCE_FILE: "files/dependencies.csv"
          TARGET_FILE: "files/data_dependencies.csv"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/libraries_io/dependencies/data_dependencies_3.csv"
          CHUNKSIZE: "100000"
          PIPELINE_NAME: "dependencies"
          RENAME_MAPPINGS: >-
            {"ID":"id","Platform":"platform","Project Name":"project_name","Project ID":"project_id","Version Number":"version_number",
            "Version ID":"version_id","Dependency Name":"dependency_name","Dependency Platform":"dependency_platform",
            "Dependency Kind":"dependency_kind","Optional Dependency":"optional_dependency",
            "Dependency Requirements":"dependency_requirements","Dependency Project ID":"dependency_project_id"}
          CSV_HEADERS: >-
            ["id","platform","project_name","project_id","version_number","version_id","dependency_name","dependency_platform",
            "dependency_kind","optional_dependency","dependency_requirements","dependency_project_id"]
        resources:
          request_memory: "4G"
          request_cpu: "1"
          request_ephemeral_storage: "10G"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_dependencies_to_bq_3"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/libraries_io/dependencies/data_dependencies_3.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "libraries_io.dependencies"
        skip_leading_rows: 2
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - name: "id"
            type: "integer"
            description: "The unique primary key of the dependency in the Libraries.io database."
            mode: "nullable"
          - name: "platform"
            type: "string"
            description: "The name of the Package manager the dependency is available on."
            mode: "nullable"
          - name: "project_name"
            type: "string"
            description: "The name of the project the dependency belongs to."
            mode: "nullable"
          - name: "project_id"
            type: "integer"
            description: "The unique primary key of the project for this dependency in the Libraries.io database."
            mode: "nullable"
          - name: "version_number"
            type: "string"
            description: "The number of the version that the dependency belongs to."
            mode: "nullable"
          - name: "version_id"
            type: "integer"
            description: "The unique primary key of the version for this dependency in the Libraries.io database."
            mode: "nullable"
          - name: "dependency_name"
            type: "string"
            description: "The name of the project that the dependency specifies."
            mode: "nullable"
          - name: "dependency_platform"
            type: "string"
            description: "The name of the package manager that the project that the dependency specifies is available from (only different for Atom)."
            mode: "nullable"
          - name: "dependency_kind"
            type: "string"
            description: "The type of dependency, often declared for the phase of usage, e.g. runtime, test, development, build."
            mode: "nullable"
          - name: "optional_dependency"
            type: "string"
            description: "Is the dependency optional?."
            mode: "nullable"
          - name: "dependency_requirements"
            type: "string"
            description: "The version or range of versions that the dependency specifies, resolution of that to a particular version is package manager specific."
            mode: "nullable"
          - name: "dependency_project_id"
            type: "integer"
            description: "The unique primary key of the project for this dependency in the Libraries.io database."
            mode: "nullable"

  graph_paths:
    - "bash_gcs_to_gcs >> [transform_dependencies,transform_dependencies_2,transform_dependencies_3] >> load_dependencies_to_bq >> load_dependencies_to_bq_2 >> load_dependencies_to_bq_3"
