# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: "bikeshare_station_info"
    description: ""

dag:
  airflow_version: 2
  initialize:
    dag_id: bikeshare_station_info
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"  # run once a week at Sunday 12am
    catchup: False
    default_view: graph

  tasks:

    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: san-francisco-bikeshare--station-info
          initial_node_count: 1
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-small
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform

    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"

      args:

        task_id: "transform_csv"
        name: "bikeshare_station_info"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: san-francisco-bikeshare--station-info
        namespace: "default"

        image_pull_policy: "Always"
        image: "{{ var.json.san_francisco_bikeshare.container_registry.bikeshare_station_info }}"
        env_vars:
          SOURCE_URL_JSON: "https://gbfs.baywheels.com/gbfs/fr/station_information"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          CHUNKSIZE: "750000"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/san_francisco_bikeshare/bikeshare_station_info/data_output.csv"
        resources:
          limit_memory: "8G"
          limit_cpu: "3"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

      args:
        task_id: "load_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/san_francisco_bikeshare/bikeshare_station_info/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "san_francisco_bikeshare.bikeshare_station_info"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - name: "station_id"
            type: "INTEGER"
            description: "Unique identifier of a station."
            mode: "REQUIRED"
          - name: "name"
            type: "STRING"
            description: "Public name of the station"
            mode: "REQUIRED"
          - name: "short_name"
            type: "STRING"
            description: "Short name or other type of identifier, as used by the data publisher"
            mode: "NULLABLE"
          - name: "lat"
            type: "FLOAT"
            description: "The latitude of station. The field value must be a valid WGS 84 latitude in decimal degrees format. See: http://en.wikipedia.org/wiki/World_Geodetic_System, https://en.wikipedia.org/wiki/Decimal_degrees"
            mode: "REQUIRED"
          - name: "lon"
            type: "FLOAT"
            description: "The longitude of station. The field value must be a valid WGS 84 longitude in decimal degrees format. See: http://en.wikipedia.org/wiki/World_Geodetic_System, https://en.wikipedia.org/wiki/Decimal_degrees"
            mode: "REQUIRED"
          - name: "region_id"
            type: "INTEGER"
            description: "ID of the region where station is located"
            mode: "NULLABLE"
          - name: "rental_methods"
            type: "STRING"
            description: "Array of enumerables containing the payment methods accepted at this station.  Current valid values (in CAPS) are: KEY (i.e. operator issued bike key / fob / card) CREDITCARD PAYPASS APPLEPAY ANDROIDPAY TRANSITCARD ACCOUNTNUMBER PHONE This list is intended to be as comprehensive at the time of publication as possible but is subject to change, as defined in File Requirements above"
            mode: "NULLABLE"
          - name: "capacity"
            type: "INTEGER"
            description: "Number of total docking points installed at this station, both available and unavailable"
            mode: "NULLABLE"
          - name: "external_id"
            type: "STRING"
            description: ""
            mode: "NULLABLE"
          - name: "eightd_has_key_dispenser"
            type: "BOOLEAN"
            description: ""
            mode: "NULLABLE"
          - name: "has_kiosk"
            type: "BOOLEAN"
            description: ""
            mode: "NULLABLE"
          - name: "station_geom"
            type: "GEOGRAPHY"
            description: ""
            mode: "NULLABLE"

    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: san-francisco-bikeshare--station-info

  graph_paths:
    - "create_cluster >> transform_csv >> load_to_bq >> delete_cluster"
