# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: "mortality_life_expectancy"
    description: "census_bureau_internationalspc"

dag:
  airflow_version: 2
  initialize:
    dag_id: mortality_life_expectancy
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:

    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"

      args:

        task_id: "transform_csv"
        name: "mortality_life_expectancy"
        namespace: "default"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: cloud.google.com/gke-nodepool
                      operator: In
                      values:
                        - "pool-e2-standard-4"
        image_pull_policy: "Always"
        image: "{{ var.json.census_bureau_international.container_registry.run_csv_transform_kub_mortality_life_expectancy }}"
        env_vars:
          SOURCE_URL: |
            "gs://pdp-feeds-staging/Census/idbzip/IDBext010.csv",
            "gs://pdp-feeds-staging/Census/idbzip/IDBextCTYS.csv"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          CHUNKSIZE: "750000"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/census_bureau_international/mortality_life_expectancy/data_output.csv"
        resources:
          limit_memory: "8G"
          limit_cpu: "3"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

      args:
        task_id: "load_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/census_bureau_international/mortality_life_expectancy/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "census_bureau_international.mortality_life_expectancy"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - name: "country_code"
            type: "STRING"
            description: "Federal Information Processing Standard (FIPS) country/area code"
            mode: "REQUIRED"
          - name: "country_name"
            type: "STRING"
            description: "Country or area name"
            mode: "NULLABLE"
          - name: "year"
            type: "INTEGER"
            description: "Year"
            mode: "REQUIRED"
          - name: "infant_mortality"
            type: "FLOAT"
            description: "Both sexes infant mortality rate (infant deaths per 1,000 population)"
            mode: "NULLABLE"
          - name: "infant_mortality_male"
            type: "FLOAT"
            description: "Male infant mortality rate (infant deaths per 1,000 population)"
            mode: "NULLABLE"
          - name: "infant_mortality_female"
            type: "FLOAT"
            description: "Female infant mortality rate (infant deaths per 1,000 population)"
            mode: "NULLABLE"
          - name: "life_expectancy"
            type: "FLOAT"
            description: "Both sexes life expectancy at birth (years)"
            mode: "NULLABLE"
          - name: "life_expectancy_male"
            type: "FLOAT"
            description: "Male life expectancy at birth (years)"
            mode: "NULLABLE"
          - name: "life_expectancy_female"
            type: "FLOAT"
            description: "Female life expectancy at birth (years)"
            mode: "NULLABLE"
          - name: "mortality_rate_under5"
            type: "FLOAT"
            description: "Both sexes under-5 mortality rate (probability of dying between ages 0 and 5)"
            mode: "NULLABLE"
          - name: "mortality_rate_under5_male"
            type: "FLOAT"
            description: "Male sexes under-5 mortality rate (probability of dying between ages 0 and 5)"
            mode: "NULLABLE"
          - name: "mortality_rate_under5_female"
            type: "FLOAT"
            description: "Female sexes under-5 mortality rate (probability of dying between ages 0 and 5)"
            mode: "NULLABLE"
          - name: "mortality_rate_1to4"
            type: "FLOAT"
            description: "Both sexes child mortality rate (probability of dying between ages 1 and 4)"
            mode: "NULLABLE"
          - name: "mortality_rate_1to4_male"
            type: "FLOAT"
            description: "Male sexes child mortality rate (probability of dying between ages 1 and 4)"
            mode: "NULLABLE"
          - name: "mortality_rate_1to4_female"
            type: "FLOAT"
            description: "Female sexes child mortality rate (probability of dying between ages 1 and 4)"
            mode: "NULLABLE"


  graph_paths:
    - "transform_csv >> load_to_bq"
