# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: crime
    description: "Chicago Crime dataset"

dag:
  airflow_version: 2
  initialize:
    dag_id: crime
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:
    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: chicago-crime--crime
          initial_node_count: 1
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-standard-2
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform

    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "chicago_crime_transform_csv"
        startup_timeout_seconds: 600
        name: "crime"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: chicago-crime--crime
        namespace: "default"
        image_pull_policy: "Always"
        image: "{{ var.json.chicago_crime.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: "https://data.cityofchicago.org/api/views/ijzp-q8t2/rows.csv"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/chicago_crime/crime/data_output.csv"
          CHUNK_SIZE: "1000000"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_chicago_crime_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/chicago_crime/crime/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "chicago_crime.crime"
        skip_leading_rows: 1
        write_disposition: "WRITE_TRUNCATE"

        schema_fields:
          - name: "unique_key"
            type: "integer"
            mode: "required"
          - name: "case_number"
            type: "string"
            mode: "nullable"
          - name: "date"
            type: "timestamp"
            mode: "nullable"
          - name: "block"
            type: "string"
            mode: "nullable"
          - name: "iucr"
            type: "string"
            mode: "nullable"
          - name: "primary_type"
            type: "string"
            mode: "nullable"
          - name: "description"
            type: "string"
            mode: "nullable"
          - name: "location_description"
            type: "string"
            mode: "nullable"
          - name: "arrest"
            type: "boolean"
            mode: "nullable"
          - name: "domestic"
            type: "boolean"
            mode: "nullable"
          - name: "beat"
            type: "integer"
            mode: "nullable"
          - name: "district"
            type: "integer"
            mode: "nullable"
          - name: "ward"
            type: "integer"
            mode: "nullable"
          - name: "community_area"
            type: "integer"
            mode: "nullable"
          - name: "fbi_code"
            type: "string"
            mode: "nullable"
          - name: "x_coordinate"
            type: "float"
            mode: "nullable"
          - name: "y_coordinate"
            type: "float"
            mode: "nullable"
          - name: "year"
            type: "integer"
          - name: "updated_on"
            type: "timestamp"
            mode: "nullable"
          - name: "latitude"
            type: "float"
            mode: "nullable"
          - name: "longitude"
            type: "float"
            mode: "nullable"
          - name: "location"
            type: "string"
            mode: "nullable"

    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: chicago-crime--crime

  graph_paths:
    - "create_cluster >> chicago_crime_transform_csv >> load_chicago_crime_to_bq >> delete_cluster"
