# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: "hourly_access"
    description: "U.S. Climate Normals Hourly Data (Most Recent)."

dag:
  airflow_version: 2
  initialize:
    dag_id: us_climate_normals
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "0 * * * *"
    catchup: False
    default_view: graph

  tasks:
    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: us-climate-normals
          initial_node_count: 2
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-standard-4
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform
    # - operator: "GoogleCloudStorageToGoogleCloudStorageOperator"
    #   description: "Copy hourly (current) source files to public bucket"
    #   args:
    #     task_id: copy_hourly_current_files_to_public_bucket
    #     source_bucket: "normals"
    #     source_object: "normals-hourly/access/*.csv"
    #     destination_bucket: "{{ var.value.composer_bucket }}"
    #     destination_object: "data/us_climate_normals/hourly_access/"
    #     move_object: False
    # - operator: "GoogleCloudStorageToGoogleCloudStorageOperator"
    #   description: "Copy hourly (historical) source files to public bucket"
    #   args:
    #     task_id: copy_hourly_historical_to_public_bucket
    #     source_bucket: "normals"
    #     source_object: "normals-hourly/1981/*.csv"
    #     destination_bucket: "{{ var.value.composer_bucket }}"
    #     destination_object: "data/us_climate_normals/hourly_access/"
    #     move_object: False
    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "us_climate_normals"
        startup_timeout_seconds: 600
        name: "load_us_climate_normals"
        namespace: "default"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: us-climate-normals
        image_pull_policy: "Always"
        image: "{{ var.json.us_climate_normals.container_registry.run_csv_transform_kub }}"
        env_vars:
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "{{ var.json.us_climate_normals.container_registry.dataset_id }}"
          CHUNKSIZE: "500000"
          CURRENT_DATA_TABLE_ID: "{{ var.json.us_climate_normals.normals_hourly.destination_dataset_table_current }}"
          HISTORICAL_DATA_TABLE_ID: "{{ var.json.us_climate_normals.normals_hourly.destination_dataset_table_historical }}"
          DATA_FILE_SURR_KEY_FIELD: "{{ var.json.us_climate_normals.normals_hourly.data_file_surr_key_field }}"
          DEST_FOLDER: "{{ var.json.us_climate_normals.container_registry.dest_folder }}"
          SCHEMA_FILEPATH: "{{ var.json.us_climate_normals.container_registry.dest_folder }}"
          SOURCE_BUCKET: "{{ var.json.us_climate_normals.container_registry.source_gcs_bucket }}"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          CURRENT_DATA_TARGET_GCS_PATH: "{{ var.json.us_climate_normals.normals_hourly.current_data_target_gcs_path }}"
          HISTORICAL_DATA_TARGET_GCS_PATH: "{{ var.json.us_climate_normals.normals_hourly.historical_data_target_gcs_path }}"
          DEST_CURRENT_DATA_FOLDER_NAME: "{{ var.json.us_climate_normals.container_registry.dest_current_data_folder_name }}"
          DEST_HISTORICAL_FOLDER_NAME: "{{ var.json.us_climate_normals.container_registry.dest_historical_data_folder_name }}"
          SOURCE_BUCKET_CURRENT_DATA_FOLDER_NAME: "{{ var.json.us_climate_normals.normals_hourly.source_bucket_current_data_folder_name }}"
          DATA_ROOT_FOLDER: "normals-hourly"
          HIST_FOLDERS_LIST: >-
            ["1981-2010", "1991-2020", "2006-2020"]
          PIPELINE_NAME: "US Climate Normals"
          INPUT_CSV_HEADERS: >-
            [ "station", "date",
              "latitude", "longitude",
              "elevation", "name",
              "hly-cldh-normal", "hly-cldh-normal_attributes",
              "hly-clod-pctbkn", "hly-clod-pctbkn_attributes",
              "hly-clod-pctclr", "hly-clod-pctclr_attributes",
              "hly-clod-pctfew", "hly-clod-pctfew_attributes",
              "hly-clod-pctovc", "hly-clod-pctovc_attributes",
              "hly-clod-pctsct","hly-clod-pctsct_attributes",
              "hly-dewp-10pctl","hly-dewp-10pctl_attributes",
              "hly-dewp-90pctl","hly-dewp-90pctl_attributes",
              "hly-dewp-normal","hly-dewp-normal_attributes",
              "hly-hidx-normal","hly-hidx-normal_attributes",
              "hly-htdh-normal","hly-htdh-normal_attributes",
              "hly-pres-10pctl","hly-pres-10pctl_attributes",
              "hly-pres-90pctl","hly-pres-90pctl_attributes",
              "hly-pres-normal","hly-pres-normal_attributes",
              "hly-temp-10pctl","hly-temp-10pctl_attributes",
              "hly-temp-90pctl","hly-temp-90pctl_attributes",
              "hly-temp-normal","hly-temp-normal_attributes",
              "hly-wchl-normal","hly-wchl-normal_attributes",
              "hly-wind-1stdir","hly-wind-1stdir_attributes",
              "hly-wind-1stpct","hly-wind-1stpct_attributes",
              "hly-wind-2nddir","hly-wind-2nddir_attributes",
              "hly-wind-2ndpct","hly-wind-2ndpct_attributes",
              "hly-wind-avgspd","hly-wind-avgspd_attributes",
              "hly-wind-pctclm","hly-wind-pctclm_attributes",
              "hly-wind-vctdir","hly-wind-vctdir_attributes",
              "hly-wind-vctspd","hly-wind-vctspd_attributes" ]
          DATA_DTYPE: >-
            { "station": "str", "date": "datetime64[ns]",
              "latitude": "float64", "longitude": "float64",
              "elevation": "float64", "name": "str",
              "hly-cldh-normal": "str", "hly-cldh-normal_attributes": "int64",
              "hly-clod-pctbkn": "str", "hly-clod-pctbkn_attributes": "int64",
              "hly-clod-pctclr": "str", "hly-clod-pctclr_attributes": "int64",
              "hly-clod-pctfew": "str", "hly-clod-pctfew_attributes": "int64",
              "hly-clod-pctovc": "str", "hly-clod-pctovc_attributes": "int64",
              "hly-clod-pctsct": "str","hly-clod-pctsct_attributes": "int64",
              "hly-dewp-10pctl": "str","hly-dewp-10pctl_attributes": "int64",
              "hly-dewp-90pctl": "str","hly-dewp-90pctl_attributes": "int64",
              "hly-dewp-normal": "str","hly-dewp-normal_attributes": "int64",
              "hly-hidx-normal": "str","hly-hidx-normal_attributes": "int64",
              "hly-htdh-normal": "str","hly-htdh-normal_attributes": "int64",
              "hly-pres-10pctl": "str","hly-pres-10pctl_attributes": "int64",
              "hly-pres-90pctl": "str","hly-pres-90pctl_attributes": "int64",
              "hly-pres-normal": "str","hly-pres-normal_attributes": "int64",
              "hly-temp-10pctl": "str","hly-temp-10pctl_attributes": "int64",
              "hly-temp-90pctl": "str","hly-temp-90pctl_attributes": "int64",
              "hly-temp-normal": "str","hly-temp-normal_attributes": "int64",
              "hly-wchl-normal": "str","hly-wchl-normal_attributes": "int64",
              "hly-wind-1stdir": "str","hly-wind-1stdir_attributes": "int64",
              "hly-wind-1stpct": "str","hly-wind-1stpct_attributes": "int64",
              "hly-wind-2nddir": "str","hly-wind-2nddir_attributes": "int64",
              "hly-wind-2ndpct": "str","hly-wind-2ndpct_attributes": "int64",
              "hly-wind-avgspd": "str","hly-wind-avgspd_attributes": "int64",
              "hly-wind-pctclm": "str","hly-wind-pctclm_attributes": "int64",
              "hly-wind-vctdir": "str","hly-wind-vctdir_attributes": "int64",
              "hly-wind-vctspd": "str","hly-wind-vctspd_attributes": "int64" }
          INT_COL_LIST: >-
            [ "hly-cldh-normal_attributes",
              "hly-clod-pctbkn_attributes",
              "hly-clod-pctclr_attributes",
              "hly-clod-pctfew_attributes",
              "hly-clod-pctovc_attributes",
              "hly-clod-pctsct_attributes",
              "hly-dewp-10pctl_attributes",
              "hly-dewp-90pctl_attributes",
              "hly-dewp-normal_attributes",
              "hly-hidx-normal_attributes",
              "hly-htdh-normal_attributes",
              "hly-pres-10pctl_attributes",
              "hly-pres-90pctl_attributes",
              "hly-pres-normal_attributes",
              "hly-temp-10pctl_attributes",
              "hly-temp-90pctl_attributes",
              "hly-temp-normal_attributes",
              "hly-wchl-normal_attributes",
              "hly-wind-1stdir_attributes",
              "hly-wind-1stpct_attributes",
              "hly-wind-2nddir_attributes",
              "hly-wind-2ndpct_attributes",
              "hly-wind-avgspd_attributes",
              "hly-wind-pctclm_attributes",
              "hly-wind-vctdir_attributes",
              "hly-wind-vctspd_attributes" ]
          # SOURCE_FILE: "files/data_green_trips.csv"
          # TARGET_FILE: "files/data_output_green_trips.csv"
          # DATA_FILE_YEAR_FIELD: "data_file_year"
          # DATA_FILE_MONTH_FIELD: "data_file_month"
          # SCHEMA_PATH: "{{ var.json.new_york_taxi_trips.container_registry.green_trips_schema_path }}"
          # CHUNKSIZE: "{{ var.json.new_york_taxi_trips.container_registry.green_trips_chunk_size }}"
          # PIPELINE_NAME: "tlc_green_trips"
          # INPUT_CSV_HEADERS: >-
          #   ["vendor_id", "pickup_datetime", "dropoff_datetime", "store_and_fwd_flag", "rate_code",
          #    "pickup_location_id", "dropoff_location_id", "passenger_count", "trip_distance", "fare_amount",
          #    "extra", "mta_tax", "tip_amount", "tolls_amount", "ehail_fee",
          #    "imp_surcharge", "total_amount", "payment_type", "trip_type", "congestion_surcharge" ]
          # DATA_DTYPES: >-
          #   { "vendor_id": "str",
          #     "pickup_datetime": "datetime64[ns]",
          #     "dropoff_datetime": "datetime64[ns]",
          #     "store_and_fwd_flag": "str",
          #     "rate_code": "str",
          #     "pickup_location_id": "str",
          #     "dropoff_location_id": "str",
          #     "passenger_count": "str",
          #     "trip_distance": "float64",
          #     "fare_amount": "float64",
          #     "extra": "float64",
          #     "mta_tax": "float64",
          #     "tip_amount": "float64",
          #     "tolls_amount": "float64",
          #     "ehail_fee": "float64",
          #     "imp_surcharge": "float64",
          #     "total_amount": "float64",
          #     "payment_type": "str",
          #     "trip_type": "str",
          #     "congestion_surcharge": "float64" }
          # OUTPUT_CSV_HEADERS: >-
          #   [ "vendor_id", "pickup_datetime", "dropoff_datetime", "store_and_fwd_flag", "rate_code",
          #     "passenger_count", "trip_distance", "fare_amount", "extra", "mta_tax",
          #     "tip_amount", "tolls_amount", "ehail_fee", "total_amount", "payment_type",
          #     "distance_between_service", "time_between_service", "trip_type", "imp_surcharge", "pickup_location_id",
          #     "dropoff_location_id", "data_file_year", "data_file_month" ]
        resources:
          request_memory: "12G"
          request_cpu: "1"
          request_ephemeral_storage: "16G"
    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: us-climate-normals

  graph_paths:
    - "copy_source_files_to_public_bucket >> hourly_access"
