# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: "hourly_access"
    description: "U.S. Climate Normals Hourly Data (Most Recent)."
  - type: bigquery_table
    table_id: "hourly_historical"
    description: "U.S. Climate Normals Hourly Data (Historical)."

dag:
  airflow_version: 2
  initialize:
    dag_id: normals_hourly
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "0 */6 * * *"
    catchup: False
    default_view: graph

  tasks:
    - operator: "BashOperator"
      description: "Task to copy over to pod, the source data and structure from GCS"
      args:
        task_id: "download_source_from_gcs"
        bash_command: |
          mkdir -p ./files/schema
          mkdir -p ./files/normals-hourly
          gsutil cp -rm gs://normals/normals-hourly * ./files/us_climate_normals/normals-hourly
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "load_data_to_bq"
        startup_timeout_seconds: 600
        name: "load_us_climate_normals_hourly_data"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.us_climate_normals.container_registry.run_csv_transform_kub }}"
        env_vars:
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "us_climate_normals"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TABLE_PREFIX: "normals_hourly"
          SOURCE_LOCAL_FOLDER_ROOT: "files/us_climate_normals"
          ROOT_GCS_FOLDER: "data/us_climate_normals"
          ROOT_PIPELINE_GS_FOLDER: "normals-hourly"
          FOLDERS_LIST: >-
            [
              "",
              "/1981-2010",
              "/1991-2020",
              "/2006-2020"
            ]
          FILE_PREFIX: >-
            [
              'AQC', 'AQW', 'CAW', 'CQC', 'FMC', 'FMW',
              'GQC', 'GQW', 'JQW', 'MQW', 'PSC', 'PSW',
              'RMC', 'RMW', 'RQC', 'RQW', 'USC', 'USW',
              'VQC', 'VQW', 'WQW'
            ]
          SCHEMA_FILEPATH_GCS_PATH_ROOT: "data/us_climate_normals/schema/normals_hourly"
        resources:
          request_memory: "12G"
          request_cpu: "1"
          request_ephemeral_storage: "16G"
  graph_paths:
    - "download_source_from_gcs >> hourly_load_historical_AQW"
