# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: "hourly_access"
    description: "U.S. Climate Normals Hourly Data (Most Recent)."

dag:
  airflow_version: 2
  initialize:
    dag_id: us_climate_normals
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "* 1 * * 6"
    catchup: False
    default_view: graph

  tasks:
    - operator: "CloudDataTransferServiceGCSToGCSOperator"
      description: "Copy source files to public bucket"
      args:
        task_id: copy_source_files_to_public_bucket
        timeout: 43200  # 12 hours
        retries: 0
        wait: True
        project_id: "{{ var.value.gcp_project }}"
        source_bucket: "{{ var.json.us_climate_normals.normals_hourly.source_gcs_bucket }}"
        source_path: "{{ var.json.us_climate_normals.normals_hourly.source_gcs_path }}"
        destination_bucket: "{{ var.value.composer_bucket }}"
        destination_path: "data/us_climate_normals/hourly_access"
        transfer_options:
          overwriteWhen: DIFFERENT
    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Load U.S. Climate Normals Hourly Data (Most Recent)"
      args:
        task_id: "hourly_access"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/us_climate_normals/hourly_access/*.csv"]
        name: "us_climate_normals.hourly_access"
        destination_project_dataset_table: '{{ var.json.us_climate_normals.normals_hourly.destination_dataset_table }}'
        source_format: 'CSV'
        create_disposition: 'CREATE_IF_NEEDED'
        write_disposition: 'WRITE_TRUNCATE'
        schema_fields:
          - name: "STATION"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "DATE"
            type: TIMESTAMP
            mode: NULLABLE
            description: ""
          - name: "LATITUDE"
            type: FLOAT
            mode: NULLABLE
            description: ""
          - name: "LONGITUDE"
            type: FLOAT
            mode: NULLABLE
            description: ""
          - name: "ELEVATION"
            type: FLOAT
            mode: NULLABLE
            description: ""
          - name: "NAME"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "HLY-CLDH-NORMAL"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-CLDH-NORMAL_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTBKN"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTBKN_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTCLR"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTCLR_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTFEW"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTFEW_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTOVC"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTOVC_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTSCT"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-CLOD-PCTSCT_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""




          - name: "HLY-DEWP-10PCTL"
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: "HLY-DEWP-10PCTL_ATTRIBUTES"
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
          - name: ""
            type: STRING
            mode: NULLABLE
            description: ""
          - name: ""
            type: INTEGER
            mode: NULLABLE
            description: ""
        resources:
          request_ephemeral_storage: "16G"
          limit_cpu: "3"

  graph_paths:
    - "hourly_access"
