# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: "tlc_yellow_trips"
    description: "New york yellow taxi trips table"

dag:
  airflow_version: 1
  initialize:
    dag_id: tlc_yellow_trips
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2021-03-01"
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph
  tasks:
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "transform_csv"
        startup_timeout_seconds: 600
        name: "load_tlc_yellow_trips"
        namespace: "default"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: cloud.google.com/gke-nodepool
                      operator: In
                      values:
                        - "pool-e2-standard-4"
        image_pull_policy: "Always"
        image: "{{ var.json.new_york_taxi_trips.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: "https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_"
          SOURCE_YEARS_TO_LOAD: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_years_to_load }}"
          SOURCE_FILE: "files/data.csv"
          TARGET_FILE: "files/data_output.csv"
          CHUNKSIZE: "1500000"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/new_york_taxi_trips/tlc_yellow_trips/data_output.csv"
          PIPELINE_NAME: "tlc_yellow_trips"
          CSV_HEADERS: >-
            ["vendor_id", "pickup_datetime", "dropoff_datetime", "passenger_count", "trip_distance", "rate_code",
             "store_and_fwd_flag", "payment_type", "fare_amount", "extra", "mta_tax", "tip_amount", "tolls_amount", "imp_surcharge",
             "total_amount", "pickup_location_id", "dropoff_location_id" ]
          DATA_DTYPES: >-
            { "vendor_id": "str",
              "pickup_datetime": "datetime64[ns]",
              "dropoff_datetime": "datetime64[ns]",
              "passenger_count": "int64",
              "trip_distance": "float64",
              "rate_code": "str",
              "store_and_fwd_flag": "str",
              "pickup_location_id": "str",
              "dropoff_location_id": "str",
              "payment_type": "str",
              "fare_amount": "float64",
              "extra": "float64",
              "mta_tax": "float64",
              "tip_amount": "float64",
              "tolls_amount": "float64",
              "imp_surcharge": "float64",
              "total_amount": "float64",
              "congestion_surcharge": "float64" }
        resources:
          request_memory: "4G"
          request_cpu: "1"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_to_bq_year_0"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_0_source_file }}"
        destination_project_dataset_table: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_0_destination_table }}"
        schema_object: "schema/new_york_taxi_trips/tlc_yellow_trips/yellow_trips_schema.json"
        source_format: "CSV"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_to_bq_year_minus_1"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_1_source_file }}"
        destination_project_dataset_table: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_1_destination_table }}"
        schema_object: "schema/new_york_taxi_trips/tlc_yellow_trips/yellow_trips_schema.json"
        source_format: "CSV"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_to_bq_year_minus_2"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_2_source_file }}"
        destination_project_dataset_table: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_2_destination_table }}"
        schema_object: "schema/new_york_taxi_trips/tlc_yellow_trips/yellow_trips_schema.json"
        source_format: "CSV"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_to_bq_year_minus_3"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_3_source_file }}"
        destination_project_dataset_table: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_3_destination_table }}"
        schema_object: "schema/new_york_taxi_trips/tlc_yellow_trips/yellow_trips_schema.json"
        source_format: "CSV"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"
    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_to_bq_year_minus_4"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_4_source_file }}"
        destination_project_dataset_table: "{{ var.json.new_york_taxi_trips.container_registry.yellow_trips_year_minus_4_destination_table }}"
        schema_object: "schema/new_york_taxi_trips/tlc_yellow_trips/yellow_trips_schema.json"
        source_format: "CSV"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"

  graph_paths:
    - "transform_csv >> load_to_bq_year_0 >> load_to_bq_year_minus_1 >> load_to_bq_year_minus_2 >> load_to_bq_year_minus_3 >> load_to_bq_year_minus_4"
