# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    # Required Properties:
    table_id: physicians_and_other_supplier_2014

    # Description of the table
    description: ":CMS-Medicare Physicians and Other Supplier 2014"

dag:

  # [Required] Specify the Airflow version of the operators used by the DAG.
  airflow_version: 1

  initialize:
    dag_id: physicians_and_other_supplier_2014
    default_args:
      owner: "Google"

      # When set to True, keeps a task from getting triggered if the previous schedule for the task hasn’t succeeded
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph

  tasks:

    - operator: "KubernetesPodOperator"

      # Task description
      description: "Run CSV transform within kubernetes pod"

      args:

        task_id: "physicians_2014_transform_csv"
        startup_timeout_seconds: 600

        # The name of the pod in which the task will run. This will be used (plus a random suffix) to generate a pod id
        name: "cms_medicare_physicians_and_other_supplier_2014"

        # The namespace to run within Kubernetes. Always set its value to "default" because we follow the guideline that KubernetesPodOperator will only be used for very light workloads, i.e. use the Cloud Composer environment's resources without starving other pipelines.
        namespace: "default"

        image_pull_policy: "Always"

        # Docker images will be built and pushed to GCR by default whenever the `scripts/generate_dag.py` is run. To skip building and pushing images, use the optional `--skip-builds` flag.
        image: "{{ var.json.cms_medicare.container_registry.run_csv_transform_kub }}"

        # Set the environment variables you need initialized in the container. Use these as input variables for the script your container is expected to perform.
        env_vars:
          SOURCE_URL: "http://download.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Medicare-Provider-Charge-Data/Downloads/Medicare_Provider_Util_Payment_PUF_CY2014.zip"
          SOURCE_FILE: "files/data.zip"
          TARGET_FILE: "files/data_output.csv"
          TARGET_GCS_BUCKET: "{{ var.json.shared.composer_bucket }}"
          TARGET_GCS_PATH: "data/cms_medicare/physicians_and_other_supplier_2014/data_output.csv"
          CSV_HEADERS: >-
           ["provider_id","provider_name","provider_street_address","provider_city","provider_state","provider_zipcode","drg_definition","hospital_referral_region_description","total_discharges","average_covered_charges","average_total_payments","average_medicare_payments"]
          RENAME_MAPPINGS: >-
           {"Provider Id": "provider_id","Provider Name": "provider_name","Provider Street Address": "provider_street_address","Provider City": "provider_city","Provider State": "provider_state","Provider Zip Code": "provider_zipcode","DRG Definition": "drg_definition","Hospital Referral Region (HRR) Description": "hospital_referral_region_description","Total Discharges": "total_discharges","Average Covered Charges": "average_covered_charges","Average Total Payments": "average_total_payments","Average Medicare Payments": "average_medicare_payments"}
          PIPELINE_NAME: "physicians_and_other_supplier_2014"

        # Set resource limits for the pod here. For resource units in Kubernetes, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
        resources:
          limit_memory: "4G"
          limit_cpu: "1"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"

      args:
        task_id: "load_physicians_2014_to_bq"

        # The GCS bucket where the CSV file is located in.
        bucket: "{{ var.json.shared.composer_bucket }}"

        # The GCS object path for the CSV file
        source_objects: ["data/cms_medicare/physicians_and_other_supplier_2014/data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "cms_medicare.physicians_and_other_supplier_2014"

        # Use this if your CSV file contains a header row
        skip_leading_rows: 1

        # How to write data to the table: overwrite, append, or write if empty
        # See https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/WriteDisposition
        write_disposition: "WRITE_TRUNCATE"

        # The BigQuery table schema based on the CSV file. For more info, see
        # https://cloud.google.com/bigquery/docs/schemas.
        # Always use snake_case and lowercase for column names, and be explicit,
        # i.e. specify modes for all columns.
        # types: "INTEGER", "TIMESTAMP", "STRING"
        schema_fields:
          - description: "The CMS Certification Number (CCN) of the provider billing for outpatient hospital services"
            name: "provider_id"
            type: "STRING"
            mode: "REQUIRED"
          - description: "The name of the provider"
            name: "provider_name"
            type: "STRING"
            mode: "NULLABLE"
          - description: "The street address in which the provider is physically located"
            name: "provider_street_address"
            type: "STRING"
            mode: "NULLABLE"
          - description: "The city in which the provider is physically located"
            name: "provider_city"
            type: "STRING"
            mode: "NULLABLE"
          - description: "The state in which the provider is physically located"
            name: "provider_state"
            type: "STRING"
            mode: "NULLABLE"
          - description: "The zip code in which the provider is physically located"
            name: "provider_zipcode"
            type: "INTEGER"
            mode: "NULLABLE"
          - description: "The code and description identifying the MS-DRG. MS-DRGs are a classification system that groups similar clinical conditions (diagnoses) and the procedures furnished by the hospital during the stay"
            name: "drg_definition"
            type: "STRING"
            mode: "REQUIRED"
          - description: "The Hospital Referral Region (HRR) in which the provider is physically located"
            name: "hospital_referral_region_description"
            type: "STRING"
            mode: "NULLABLE"
          - description: "The number of discharges billed by the provider for inpatient hospital services"
            name: "total_discharges"
            type: "INTEGER"
            mode: "NULLABLE"
          - description: "The provider's average charge for services covered by Medicare for all discharges in the MS-DRG. These will vary from hospital to hospital because of differences in hospital charge structures"
            name: "average_covered_charges"
            type: "FLOAT"
            mode: "NULLABLE"
          - description: "The average total payments to all providers for the MS-DRG including the MSDRG amount, teaching, disproportionate share, capital, and outlier payments for all cases. Also included 5 in average total payments are co-payment and deductible amounts that the patient is responsible for and any additional payments by third parties for coordination of benefits"
            name: "average_total_payments"
            type: "FLOAT"
            mode: "NULLABLE"
          - description: "The average amount that Medicare pays to the provider for Medicare's share of the MS-DRG. Average Medicare payment amounts include the MS-DRG amount, teaching, disproportionate share, capital, and outlier payments for all cases. Medicare payments DO NOT include beneficiary co-payments and deductible amounts nor any additional payments from third parties for coordination of benefits"
            name: "average_medicare_payments"
            type: "FLOAT"
            mode: "NULLABLE"

  graph_paths:
    - "physicians_2014_transform_csv >> load_physicians_2014_to_bq"
