# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: institutions
    description: "FDIC table"

dag:
  airflow_version: 2
  initialize:
    dag_id: institutions
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2022-09-28"
    max_active_runs: 1
    schedule_interval: "@daily"
    catchup: False
    default_view: graph
  tasks:
    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "institutions"
        startup_timeout_seconds: 600
        name: "transform_institutions_to_csv"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.fdic.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_URL: "https://s3-us-gov-west-1.amazonaws.com/cg-2e5c99a6-e282-42bf-9844-35f5430338a5/downloads/institutions.csv"
          SOURCE_FILE: "files/institutions.csv"
          TARGET_FILE: "files/data_output.csv"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/fdic/data_output_institutions.csv"
          PIPELINE_NAME: "institutions"
          CSV_HEADERS: >-
            ['fdic_certificate_number', 'institution_name', 'state_name', 'fdic_id', 'docket', 'active', 'address',
            'total_assets', 'bank_charter_class', 'change_code_1', 'change_code_2', 'change_code_3', 'change_code_4',
            'change_code_5', 'change_code_6', 'change_code_7', 'change_code_8', 'change_code_9', 'change_code_10', 
            'change_code_11', 'change_code_12', 'change_code_13', 'change_code_14', 'change_code_15', 'occ_charter', 
            'chartering_agency', 'conservatorship', 'city', 'category_code', 'county_fips_code', 'county_name', 
            'established_date', 'last_updated', 'effective_date', 'end_effective_date', 'denovo_institute', 
            'total_deposits', 'equity_capital', 'fdic_geo_region', 'fdic_supervisory_region', 'fdic_supervisory_region_code', 
            'fed_reserve_district', 'fed_reserve_district_id', 'fed_reserve_unique_id', 'federal_charter', 
            'fdic_field_office', 'iba', 'inactive_flag', 'insurance_fund_membership', 'secondary_insurance_fund', 
            'deposit_insurance_date', 'credit_card_institution', 'bank_insurance_fund_member', 'insured_commercial_bank', 
            'deposit_insurance_fund_member', 'fdic_insured', 'saif_insured', 'insured_savings_institute', 'new_cert_number', 
            'oakar_institute', 'ots_region', 'last_structural_change', 'qbp_region', 'regulator', 'report_date', 
            'reporting_period_end_date', 'state_chartered', 'return_on_assets', 'roa_quarterly', 'roa_pretax', 
            'row_pretax_quarterly', 'return_on_equity', 'roe_quarterly', 'run_date', 'sasser_institute', 'law_sasser', 
            'state', 'state_fips_code', 'trade_name_1', 'trade_name_2', 'trade_name_3', 'trade_name_4', 'trade_name_5', 
            'trade_name_6', 'zip_code', 'occ_district', 'ultimate_cert_number', 'cfpb_supervisory_flag', 
            'cfpb_supervisory_start_date', 'cfpb_supervisory_end_date', 'offices_count', 'parent_fdic_cert', 
            'parent_parcert', 'high_holder_city', 'total_domestic_deposits', 'ffiec_call_report_filer', 'holding_company_flag', 
            'ag_lending_flag', 'ownership_type', 'top_holder', 'net_income', 'quarterly_net_income', 'office_count_domestic', 
            'office_count_foreign', 'office_count_us_territories', 'rssd_id', 'holding_company_state', 'subchap_s_indicator', 
            'trust_powers_status', 'asset_concentration_hierarchy', 'primary_specialization', 'csa_name', 'csa_fips_code', 
            'csa_indicator', 'cbsa_name', 'cbsa_fips_code', 'cbsa_metro_flag', 'cbsa_micro_flag', 'cbsa_division_name', 
            'cbsa_division_fips_code', 'cbsa_division_flag']
        resources:
          request_memory: "4G"
          request_cpu: "1"
          request_ephemeral_storage: "10G"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_institutions_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/fdic/data_output_institutions.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "fdic.institutions"
        skip_leading_rows: 1
        allow_quoted_newlines: True
        write_disposition: "WRITE_TRUNCATE"

        schema_fields:
          - name: "fdic_certificate_number"
            type: "string"
            description: "A unique number assigned by the FDIC used to identify institutions and for the issuance of insurance certificates."
            mode: "nullable"
          - name: "institution_name"
            type: "string"
            description: "The legal name of the institution."
            mode: "nullable"
          - name: "branch_name"
            type: "string"
            description: "Name of the branch."
            mode: "nullable"
          - name: "branch_number"
            type: "string"
            description: "The branch's corresponding office number."
            mode: "nullable"
          - name: "main_office"
            type: "boolean"
            description: "The main office for the institution."
            mode: "nullable"
          - name: "branch_address"
            type: "string"
            description: "Street address at which the branch is physically located."
            mode: "nullable"
          - name: "branch_city"
            type: "string"
            description: "City in which branch is physically located."
            mode: "nullable"
          - name: "zip_code"
            type: "string"
            description: "The first five digits of the full postal zip code representing physical location of the branch."
            mode: "nullable"
          - name: "branch_county"
            type: "string"
            description: "County where the branch is physically located."
            mode: "nullable"
          - name: "county_fips_code"
            type: "string"
            description: "A five digit number representing the state and county in which the institution is physically located.  The first two digits represent the FIPS state numeric code and the last three digits represent the FIPS county numeric code."
            mode: "nullable"
          - name: "state"
            type: "string"
            description: "State abbreviation in which the branch is physically located. The FDIC Act defines state as any State of the United States the District of Columbia and any territory of the United States Puerto Rico Guam American Samoa the Trust Territory of the Pacific Islands the Virgin Island and the Northern Mariana Islands."
            mode: "nullable"
          - name: "state_name"
            type: "string"
            description: "State in which the  branch is physically located. The FDIC Act defines state as any State of the United States the District of Columbia and any territory of the United States Puerto Rico Guam American Samoa the Trust Territory of the Pacific Islands the Virgin Island and the Northern Mariana Islands."
            mode: "nullable"
          - name: "institution_class"
            type: "string"
            description: "\"A classification code assigned by the FDIC based on the institution's charter type (commercial bank or savings institution) charter agent (state or federal) Federal Reserve membership status (Fed member Fed nonmember) and its primary federal regulator (state chartered institutions are subject to both federal and state supervision). N -Commercial bank national (federal) charter and Fed member supervised by the Office of the Comptroller of the Currency (OCC) NM -Commercial bank state charter and Fed nonmember supervised by the FDIC OI - Insured U.S. branch of a foreign chartered institution (IBA) SA - Savings associations state or federal charter supervised by the Office of Thrift Supervision (OTS) SB - Savings banks state charter supervised by the FDIC SM - Commercial bank state charter and Fed member supervised by the Federal Reserve (FRB)\""
            mode: "nullable"
          - name: "cbsa_fips_code"
            type: "string"
            description: "Numeric code of the Core Based Statistical Area (CBSA) as defined by the US Census Bureau Office of Management and Budget."
            mode: "nullable"
          - name: "cbsa_name"
            type: "string"
            description: "Name of the Core Based Statistical Area (CBSA) as defined by the US Census Bureau Office of Management and Budget."
            mode: "nullable"
          - name: "cbsa_division_flag"
            type: "boolean"
            description: "A flag indicating member of a Core Based Statistical Division as defined by the US Census Bureau Office of Management and Budget."
            mode: "nullable"
          - name: "cbsa_division_fips_code"
            type: "integer"
            description: "Numeric code of the Core Based Statistical Division as defined by the US Census Bureau Office of Management and Budget."
            mode: "nullable"
          - name: "cbsa_division_name"
            type: "string"
            description: "Name of the Core Based Statistical Division as defined by the US Census Bureau Office of Management and Budget."
            mode: "nullable"
          - name: "cbsa_metro_flag"
            type: "boolean"
            description: "A flag used to indicate whether an branch is in a Metropolitan Statistical Area as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "cbsa_metro_fips_code"
            type: "string"
            description: "Numeric code of the Metropolitan Statistical Area as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "cbsa_metro_name"
            type: "string"
            description: "Name of the Metropolitan Statistical Area as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "cbsa_micro_flag"
            type: "boolean"
            description: "A flag (1=Yes) used to indicate whether an branch is in a Micropolitan Statistical Area as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "csa_flag"
            type: "boolean"
            description: "Flag (1=Yes) indicating member of a Combined Statistical Area (CSA) as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "csa_fips_code"
            type: "string"
            description: "Numeric code of the Combined Statistical Area (CSA) as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "csa_name"
            type: "string"
            description: "Name of the Combined Statistical Area (CSA) as defined by the US Census Bureau Office of Management and Budget"
            mode: "nullable"
          - name: "date_established"
            type: "date"
            description: "The date on which the branch began operations."
            mode: "nullable"
          - name: "fdic_uninum"
            type: "string"
            description: "This is the FDIC UNINUM of the institution that owns the branch. A UNINUM is a unique sequentially number added to the FDIC database for both banks and branches. There is no pattern imbedded within the number. The FI_UNINUM is updated with every merger or purchase of branches to reflect the most current owner."
            mode: "nullable"
          - name: "last_updated"
            type: "date"
            description: "The day the institution information was updated."
            mode: "nullable"
          - name: "service_type"
            type: "string"
            description: "\"Define the various types of offices of FDIC-insured institutions. 11 -  Full Service Brick and Mortar Office 12 -  Full Service Retail Office 13 -  Full Service Cyber Office 14 -  Full Service Mobile Office 15 -  Full Service Home/Phone Banking 16 -  Full Service Seasonal Office 21 -  Limited Service Administrative Office 22 -  Limited Service Military Facility 23 -  Limited Service Facility Office 24 -  Limited Service Loan Production Office 25 -  Limited Service Consumer Credit Office 26 -  Limited Service Contractual Office 27 -  Limited Service Messenger Office 28 -  Limited Service Retail Office 29 -  Limited Service Mobile Office 30 -  Limited Service Trust Office\""
            mode: "nullable"
          - name: "branch_fdic_uninum"
            type: "string"
            description: "Unique Identification Number for a Branch Office as assigned by the FDIC"
            mode: "nullable"

  graph_paths:
    - "transform_institutions_to_csv >> load_institutions_to_bq"
