# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

resources: ~

dag:
  airflow_version: 2
  initialize:
    dag_id: idc_tcia_transfer_bq_data
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "@monthly"
    catchup: False
    default_view: graph

  tasks:

  #   - operator: "GoogleCloudStorageToGoogleCloudStorageOperator"

  #     # Task description
  #     description: "Task to run a GoogleCloudStorageToGoogleCloudStorageOperator"

  #     args:
  #       # Arguments supported by this operator:
  #       # https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/transfers/gcs_to_gcs/index.html

  #       task_id: "transfer_image_files"

  #       # The GCS bucket to copy the object/s from
  #       source_bucket: "{{ var.json.idc.source_bucket }}"

  #       # Use a trailing "/*" if you want to copy all objects under that path.
  #       source_object: "{{ var.json.idc.source_object }}"

  #       # The GCS bucket to copy the object/s to
  #       destination_bucket: "{{ var.json.idc.destination_bucket }}"

  #       # The GCS prefix to copy the object/s to
  #       destination_object: "{{ var.json.idc.destination_path }}"

  #       # Use this argument if you don't want to keep the source object/s.
  #       move_object: False

  #       # Whether you want to replace existing destination files or not.
  #       replace: False

  #       impersonation_chain: "{{ var.json.idc.impersonation_account }}"

  # graph_paths:
  #   - "transfer_image_files"
