# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:

  - type: bigquery_table
    table_id: metadata
    description: "It contains metadata of all existing audio files in tabular format."

dag:
  airflow_version: 2
  initialize:
    dag_id: mswc
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: "2021-03-01"
    max_active_runs: 1
    schedule_interval: "@quarterly"
    catchup: False
    default_view: graph

  tasks:

    - operator: "GoogleCloudStorageToGoogleCloudStorageOperator"
      description: "Task to run a GCS to GCS"
      args:
        task_id: "copy_metadata_file_to_bucket"
        source_bucket: "{{ var.json.mswc.source_bucket }}"
        source_object: "metadata.json.gz"
        destination_bucket: "{{ var.value.composer_bucket }}"
        destination_object: "data/mswc/metadata.json.gz"
        move_object: False

    - operator: "BashOperator"
      description: "Task to unzip tar file"
      args:
        task_id: "unzip_metadata_gz"
        bash_command: |
          echo Unzipping $data_dir/$source_file...
          gunzip -c $data_dir/$source_file > $data_dir/metadata.json
          echo Successfully unzipped .gz file to specified file metadata.json
        env:
          data_dir: "/home/airflow/gcs/data/mswc"
          source_file: "metadata.json.gz"
          source_bucket: "{{ var.json.mswc.source_bucket }}"

    - operator: "KubernetesPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "metadata_csv_transform"
        startup_timeout_seconds: 600
        name: "metadata_csv_transform"
        namespace: "composer"
        service_account_name: "datasets"
        image_pull_policy: "Always"
        image: "{{ var.json.mswc.container_registry.run_csv_transform_kub }}"
        env_vars:
          SOURCE_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          SOURCE_GCS_OBJECT: "data/mswc/metadata.json"
          SOURCE_FILE: "./files/metadata.json"
          TARGET_CSV_FILE: "./files/metadata_data_output.csv"
          COLUMNS: >-
            ["lang_abbr", "language", "number_of_words","word", "word_count", "filename"]
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          TARGET_GCS_PATH: "data/mswc/metadata_data_output.csv"
        resources:
          request_memory: "4G"
          request_cpu: "1"
          request_ephemeral_storage: "4G"

    - operator: "GoogleCloudStorageToBigQueryOperator"
      description: "Task to load CSV data to a BigQuery table"
      args:
        task_id: "load_metadata_to_bq"
        bucket: "{{ var.value.composer_bucket }}"
        source_objects: ["data/mswc/metadata_data_output.csv"]
        source_format: "CSV"
        destination_project_dataset_table: "mswc.metadata"
        skip_leading_rows: 1
        write_disposition: "WRITE_TRUNCATE"
        schema_fields:
          - name: "lang_abbr"
            type: "string"
            description: "It consists of language abbrevation."
            mode: "nullable"
          - name: "language"
            type: "string"
            description: "It consists of language name."
            mode: "nullable"
          - name: "number_of_words"
            type: "integer"
            description: "It consists count of total number of words for corresponding language."
            mode: "nullable"
          - name: "word"
            type: "string"
            description: "It contains words of each corresponding language."
            mode: "nullable"
          - name: "word_count"
            type: "integer"
            description: "It consists word count for each word in corresponding language"
            mode: "nullable"
          - name: "filename"
            type: "string"
            description: "It consists filenames for corresponding word in specific language."
            mode: "nullable"

  graph_paths:
    - "copy_metadata_file_to_bucket >> unzip_metadata_gz >> metadata_csv_transform >> load_metadata_to_bq"
