# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
resources:
  - type: bigquery_table
    table_id: "daily_access"
    description: "U.S. Climate Normals Daily Data (Most Recent)."
  - type: bigquery_table
    table_id: "daily_historical"
    description: "U.S. Climate Normals Daily Data (Historical)."

dag:
  airflow_version: 2
  initialize:
    dag_id: normals_daily
    default_args:
      owner: "Google"
      depends_on_past: False
      start_date: '2021-03-01'
    max_active_runs: 1
    schedule_interval: "0 2 * * *"  # Every day at 2am
    catchup: False
    default_view: graph

  tasks:
    - operator: "GKECreateClusterOperator"
      args:
        task_id: "create_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        body:
          name: us-climate-normals-daily
          initial_node_count: 2
          network: "{{ var.value.vpc_network }}"
          node_config:
            machine_type: e2-standard-4
            oauth_scopes:
              - https://www.googleapis.com/auth/devstorage.read_write
              - https://www.googleapis.com/auth/cloud-platform
    - operator: "GKEStartPodOperator"
      description: "Run CSV transform within kubernetes pod"
      args:
        task_id: "daily_load"
        startup_timeout_seconds: 600
        name: "load_us_climate_normals"
        namespace: "default"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        cluster_name: us-climate-normals-daily
        image_pull_policy: "Always"
        image: "{{ var.json.us_climate_normals.container_registry.run_csv_transform_kub }}"
        env_vars:
          PROJECT_ID: "{{ var.value.gcp_project }}"
          DATASET_ID: "{{ var.json.us_climate_normals.container_registry.dataset_id }}"
          CHUNKSIZE: "500000"
          CURRENT_DATA_TABLE_ID: "{{ var.json.us_climate_normals.normals_daily.destination_dataset_table_current }}"
          HISTORICAL_DATA_TABLE_ID: "{{ var.json.us_climate_normals.normals_daily.destination_dataset_table_historical }}"
          DATA_FILE_SURR_KEY_FIELD: "{{ var.json.us_climate_normals.normals_daily.data_file_surr_key_field }}"
          DEST_FOLDER: "{{ var.json.us_climate_normals.container_registry.dest_folder }}"
          SCHEMA_FILEPATH: "{{ var.json.us_climate_normals.normals_daily.schema_filepath }}"
          SOURCE_BUCKET: "{{ var.json.us_climate_normals.container_registry.source_gcs_bucket }}"
          TARGET_GCS_BUCKET: "{{ var.value.composer_bucket }}"
          CURRENT_DATA_TARGET_GCS_PATH: "{{ var.json.us_climate_normals.normals_daily.current_data_target_gcs_path }}"
          HISTORICAL_DATA_TARGET_GCS_PATH: "{{ var.json.us_climate_normals.normals_daily.historical_data_target_gcs_path }}"
          DEST_CURRENT_DATA_FOLDER_NAME: "{{ var.json.us_climate_normals.container_registry.dest_current_data_folder_name }}"
          DEST_HISTORICAL_FOLDER_NAME: "{{ var.json.us_climate_normals.container_registry.dest_historical_data_folder_name }}"
          SOURCE_BUCKET_CURRENT_DATA_FOLDER_NAME: "{{ var.json.us_climate_normals.normals_daily.source_bucket_current_data_folder_name }}"
          DATA_ROOT_FOLDER: "normals-daily"
          HIST_FOLDERS_LIST: >-
            ["1981-2010", "1991-2020", "2006-2020"]
          PIPELINE_NAME: "US Climate Normals Daily Load"
          INPUT_CSV_HEADERS: >-
            [ "station", "date",
              "latitude", "longitude",
              "elevation", "name",
              "hly-cldh-normal", "hly-cldh-normal_attributes",
              "hly-clod-pctbkn", "hly-clod-pctbkn_attributes",
              "hly-clod-pctclr", "hly-clod-pctclr_attributes",
              "hly-clod-pctfew", "hly-clod-pctfew_attributes",
              "hly-clod-pctovc", "hly-clod-pctovc_attributes",
              "hly-clod-pctsct","hly-clod-pctsct_attributes",
              "hly-dewp-10pctl","hly-dewp-10pctl_attributes",
              "hly-dewp-90pctl","hly-dewp-90pctl_attributes",
              "hly-dewp-normal","hly-dewp-normal_attributes",
              "hly-hidx-normal","hly-hidx-normal_attributes",
              "hly-htdh-normal","hly-htdh-normal_attributes",
              "hly-pres-10pctl","hly-pres-10pctl_attributes",
              "hly-pres-90pctl","hly-pres-90pctl_attributes",
              "hly-pres-normal","hly-pres-normal_attributes",
              "hly-temp-10pctl","hly-temp-10pctl_attributes",
              "hly-temp-90pctl","hly-temp-90pctl_attributes",
              "hly-temp-normal","hly-temp-normal_attributes",
              "hly-wchl-normal","hly-wchl-normal_attributes",
              "hly-wind-1stdir","hly-wind-1stdir_attributes",
              "hly-wind-1stpct","hly-wind-1stpct_attributes",
              "hly-wind-2nddir","hly-wind-2nddir_attributes",
              "hly-wind-2ndpct","hly-wind-2ndpct_attributes",
              "hly-wind-avgspd","hly-wind-avgspd_attributes",
              "hly-wind-pctclm","hly-wind-pctclm_attributes",
              "hly-wind-vctdir","hly-wind-vctdir_attributes",
              "hly-wind-vctspd","hly-wind-vctspd_attributes" ]
          DATA_DTYPE: >-
            { "station": "str", "date": "str",
              "latitude": "float64", "longitude": "float64",
              "elevation": "float64", "name": "str",
              "hly-cldh-normal": "str", "hly-cldh-normal_attributes": "str",
              "hly-clod-pctbkn": "str", "hly-clod-pctbkn_attributes": "str",
              "hly-clod-pctclr": "str", "hly-clod-pctclr_attributes": "str",
              "hly-clod-pctfew": "str", "hly-clod-pctfew_attributes": "str",
              "hly-clod-pctovc": "str", "hly-clod-pctovc_attributes": "str",
              "hly-clod-pctsct": "str","hly-clod-pctsct_attributes": "str",
              "hly-dewp-10pctl": "str","hly-dewp-10pctl_attributes": "str",
              "hly-dewp-90pctl": "str","hly-dewp-90pctl_attributes": "str",
              "hly-dewp-normal": "str","hly-dewp-normal_attributes": "str",
              "hly-hidx-normal": "str","hly-hidx-normal_attributes": "str",
              "hly-htdh-normal": "str","hly-htdh-normal_attributes": "str",
              "hly-pres-10pctl": "str","hly-pres-10pctl_attributes": "str",
              "hly-pres-90pctl": "str","hly-pres-90pctl_attributes": "str",
              "hly-pres-normal": "str","hly-pres-normal_attributes": "str",
              "hly-temp-10pctl": "str","hly-temp-10pctl_attributes": "str",
              "hly-temp-90pctl": "str","hly-temp-90pctl_attributes": "str",
              "hly-temp-normal": "str","hly-temp-normal_attributes": "str",
              "hly-wchl-normal": "str","hly-wchl-normal_attributes": "str",
              "hly-wind-1stdir": "str","hly-wind-1stdir_attributes": "str",
              "hly-wind-1stpct": "str","hly-wind-1stpct_attributes": "str",
              "hly-wind-2nddir": "str","hly-wind-2nddir_attributes": "str",
              "hly-wind-2ndpct": "str","hly-wind-2ndpct_attributes": "str",
              "hly-wind-avgspd": "str","hly-wind-avgspd_attributes": "str",
              "hly-wind-pctclm": "str","hly-wind-pctclm_attributes": "str",
              "hly-wind-vctdir": "str","hly-wind-vctdir_attributes": "str",
              "hly-wind-vctspd": "str","hly-wind-vctspd_attributes": "str" }
          INT_COL_LIST: >-
            [ "hly-cldh-normal",
              "hly-clod-pctbkn",
              "hly-clod-pctclr",
              "hly-clod-pctfew",
              "hly-clod-pctovc",
              "hly-clod-pctsct",
              "hly-dewp-10pctl",
              "hly-dewp-90pctl",
              "hly-dewp-normal",
              "hly-hidx-normal",
              "hly-htdh-normal",
              "hly-pres-10pctl",
              "hly-pres-90pctl",
              "hly-pres-normal",
              "hly-temp-10pctl",
              "hly-temp-90pctl",
              "hly-temp-normal",
              "hly-wchl-normal",
              "hly-wind-1stdir",
              "hly-wind-1stpct",
              "hly-wind-2nddir",
              "hly-wind-2ndpct",
              "hly-wind-avgspd",
              "hly-wind-pctclm",
              "hly-wind-vctdir",
              "hly-wind-vctspd" ]
        resources:
          request_memory: "12G"
          request_cpu: "1"
          request_ephemeral_storage: "16G"
    - operator: "GKEDeleteClusterOperator"
      args:
        task_id: "delete_cluster"
        project_id: "{{ var.value.gcp_project }}"
        location: "us-central1-c"
        name: us-climate-normals-daily

  graph_paths:
    - "create_cluster >> daily_load >> delete_cluster"
