name: Lint Python
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run:
          python -m pip install flake8 isort nbqa black[jupyter]
      - uses: psf/black@20.8b1
          python -m pip install flake8 isort
      - uses: psf/black@stable
        with:
          args: ". --check"
          version: "21.5b1"
      - name: Run Flake8 Linter
        run: flake8
      - name: Run isort
        run: isort --check-only --profile black --diff .
      - name: Run flake8 on notebooks
        run: nbqa flake8 .
