name: Run unit tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.1
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --ignore-pipfile --dev
      - name: Initialize Airflow
        run: pipenv run airflow db init
      - name: Run tests
        run: pipenv run python -m pytest -v
